// BBC 800 Essential Words - Functional Words (176 Words)
const vocabulary = [
    { "english": "The", "turkish": "Belirli tanımlık", "englishSentence": "The book on the table is mine.", "turkishSentence": "Masadaki kitap benimdir." },
    { "english": "Which", "turkish": "Hangi / Hangisi", "englishSentence": "Which color do you prefer?", "turkishSentence": "Hangi rengi tercih edersin?" },
    { "english": "Still", "turkish": "Hâlâ / Yine de", "englishSentence": "It is late, but he is still working.", "turkishSentence": "Vakit geç oldu ama o hâlâ çalışıyor." },
    { "english": "Although", "turkish": "Rağmen / Karşın", "englishSentence": "Although it was raining, they went for a walk.", "turkishSentence": "Yağmur yağmasına rağmen yürüyüşe çıktılar." },
    { "english": "And", "turkish": "Ve", "englishSentence": "I bought apples and oranges.", "turkishSentence": "Elma ve portakal satın aldım." },
    { "english": "Up", "turkish": "Yukarı / Yukarıya", "englishSentence": "Please look up at the stars.", "turkishSentence": "Lütfen yukarıdaki yıldızlara bak." },
    { "english": "Last", "turkish": "Son / Geçen", "englishSentence": "I saw him last week.", "turkishSentence": "Onu geçen hafta gördüm." },
    { "english": "Past", "turkish": "Geçmiş", "englishSentence": "We learn from the past.", "turkishSentence": "Geçmişten ders çıkarırız." },
    { "english": "Forty", "turkish": "Kırk", "englishSentence": "She is forty years old.", "turkishSentence": "O kırk yaşında." },
    { "english": "Nobody", "turkish": "Hiç kimse", "englishSentence": "Nobody knows the answer.", "turkishSentence": "Hiç kimse cevabı bilmiyor." },
    { "english": "Of", "turkish": "-ın, -in eki / Parçası", "englishSentence": "The roof of the house is red.", "turkishSentence": "Evin çatısı kırmızıdır." },
    { "english": "Out", "turkish": "Dışarı / Dışarıda", "englishSentence": "Let's go out for dinner tonight.", "turkishSentence": "Bu gece akşam yemeği için dışarı çıkalım." },
    { "english": "Being", "turkish": "Olmak / Varlık", "englishSentence": "Being honest is important.", "turkishSentence": "Dürüst olmak önemlidir." },
    { "english": "Himself", "turkish": "Kendisi (erkek)", "englishSentence": "He did it himself.", "turkishSentence": "Onu kendisi yaptı." },
    { "english": "Unless", "turkish": "Olmadıkça / -medikçe", "englishSentence": "Unless you study, you will fail.", "turkishSentence": "Çalışmadıkça başarısız olursun." },
    { "english": "To", "turkish": "-e, -a yönelme eki", "englishSentence": "I am going to the office now.", "turkishSentence": "Şimdi ofise gidiyorum." },
    { "english": "Would", "turkish": "-ecekti / -ardı", "englishSentence": "I would like some tea.", "turkishSentence": "Biraz çay isterdim." },
    { "english": "Must", "turkish": "Zorunda / -meli", "englishSentence": "You must follow the rules.", "turkishSentence": "Kurallara uymalısın." },
    { "english": "Seven", "turkish": "Yedi", "englishSentence": "There are seven days in a week.", "turkishSentence": "Bir haftada yedi gün vardır." },
    { "english": "Mine", "turkish": "Benimki", "englishSentence": "This book is mine.", "turkishSentence": "Bu kitap benimki." },
    { "english": "A", "turkish": "Bir (belirsiz tanımlık)", "englishSentence": "I need a pen.", "turkishSentence": "Bir kaleme ihtiyacım var." },
    { "english": "When", "turkish": "Ne zaman", "englishSentence": "When will the meeting start?", "turkishSentence": "Toplantı ne zaman başlayacak?" },
    { "english": "Another", "turkish": "Başka bir / Bir diğer", "englishSentence": "Can I have another chance?", "turkishSentence": "Başka bir şans alabilir miyim?" },
    { "english": "Eight", "turkish": "Sekiz", "englishSentence": "The class starts at eight.", "turkishSentence": "Ders sekizde başlıyor." },
    { "english": "Anybody", "turkish": "Herhangi biri", "englishSentence": "Is anybody home?", "turkishSentence": "Evde kimse var mı?" },
    { "english": "I", "turkish": "Ben", "englishSentence": "I am a student.", "turkishSentence": "Ben bir öğrenciyim." },
    { "english": "Your", "turkish": "Senin / Sizin", "englishSentence": "What is your name?", "turkishSentence": "Senin adın ne?" },
    { "english": "Between", "turkish": "Arasında", "englishSentence": "The park is between the two buildings.", "turkishSentence": "Park iki binanın arasında." },
    { "english": "Along", "turkish": "Boyunca", "englishSentence": "We walked along the river.", "turkishSentence": "Nehir boyunca yürüdük." },
    { "english": "Till", "turkish": "Kadar / -e kadar", "englishSentence": "Wait till I come back.", "turkishSentence": "Ben dönene kadar bekle." },
    { "english": "In", "turkish": "İçinde / -de, -da", "englishSentence": "The keys are in my pocket.", "turkishSentence": "Anahtarlar cebimde." },
    { "english": "Will", "turkish": "Gelecek zaman eki / İrade", "englishSentence": "I will call you tomorrow.", "turkishSentence": "Yarın seni arayacağım." },
    { "english": "Might", "turkish": "Olabilir / -ebilir", "englishSentence": "It might rain tonight.", "turkishSentence": "Bu gece yağmur yağabilir." },
    { "english": "Round", "turkish": "Yuvarlak / Etrafında", "englishSentence": "The earth is round.", "turkishSentence": "Dünya yuvarlaktır." },
    { "english": "Herself", "turkish": "Kendisi (kadın)", "englishSentence": "She made it herself.", "turkishSentence": "Onu kendisi yaptı." },
    { "english": "You", "turkish": "Sen / Siz", "englishSentence": "You are my best friend.", "turkishSentence": "Sen benim en iyi arkadaşımsın." },
    { "english": "Their", "turkish": "Onların", "englishSentence": "Their house is very big.", "turkishSentence": "Onların evi çok büyük." },
    { "english": "Both", "turkish": "Her ikisi de", "englishSentence": "Both answers are correct.", "turkishSentence": "Her iki cevap da doğru." },
    { "english": "Several", "turkish": "Birkaç / Çeşitli", "englishSentence": "I have several books to read.", "turkishSentence": "Okuyacak birkaç kitabım var." },
    { "english": "Twelve", "turkish": "On iki", "englishSentence": "There are twelve months in a year.", "turkishSentence": "Bir yılda on iki ay vardır." },
    { "english": "That", "turkish": "O / Şu / Ki", "englishSentence": "I know that you are right.", "turkishSentence": "Haklı olduğunu biliyorum." },
    { "english": "Who", "turkish": "Kim", "englishSentence": "Who is at the door?", "turkishSentence": "Kapıda kim var?" },
    { "english": "Five", "turkish": "Beş", "englishSentence": "I have five siblings.", "turkishSentence": "Beş kardeşim var." },
    { "english": "Someone", "turkish": "Birisi", "englishSentence": "Someone left a message for you.", "turkishSentence": "Birisi sana mesaj bıraktı." },
    { "english": "Fifteen", "turkish": "On beş", "englishSentence": "The bus comes in fifteen minutes.", "turkishSentence": "Otobüs on beş dakika sonra gelecek." },
    { "english": "It", "turkish": "O (cansız)", "englishSentence": "It is a beautiful day.", "turkishSentence": "Güzel bir gün." },
    { "english": "Some", "turkish": "Bazı / Biraz", "englishSentence": "Can I have some water?", "turkishSentence": "Biraz su alabilir miyim?" },
    { "english": "Four", "turkish": "Dört", "englishSentence": "I have four brothers.", "turkishSentence": "Dört erkek kardeşim var." },
    { "english": "Whatever", "turkish": "Her ne / Ne olursa olsun", "englishSentence": "Whatever you decide, I support you.", "turkishSentence": "Ne karar verirsen ver, seni destekliyorum." },
    { "english": "Beyond", "turkish": "Ötesinde", "englishSentence": "The village is beyond the mountains.", "turkishSentence": "Köy dağların ötesinde." },
    { "english": "For", "turkish": "İçin / -den dolayı", "englishSentence": "This gift is for you.", "turkishSentence": "Bu hediye senin için." },
    { "english": "Two", "turkish": "İki", "englishSentence": "I have two cats.", "turkishSentence": "İki kedim var." },
    { "english": "Around", "turkish": "Etrafında / Civarında", "englishSentence": "There are trees around the house.", "turkishSentence": "Evin etrafında ağaçlar var." },
    { "english": "Among", "turkish": "Arasında (çoğul)", "englishSentence": "She is among the best students.", "turkishSentence": "O en iyi öğrenciler arasında." },
    { "english": "Whom", "turkish": "Kimi / Kime", "englishSentence": "To whom did you give the letter?", "turkishSentence": "Mektubu kime verdin?" },
    { "english": "He", "turkish": "O (erkek)", "englishSentence": "He is a good person.", "turkishSentence": "O iyi bir insandır." },
    { "english": "Because", "turkish": "Çünkü", "englishSentence": "I stayed home because I was sick.", "turkishSentence": "Hasta olduğum için evde kaldım." },
    { "english": "While", "turkish": "İken / Sırasında", "englishSentence": "I fell asleep while watching TV.", "turkishSentence": "TV izlerken uyuyakaldım." },
    { "english": "Across", "turkish": "Karşısında / Boydan boya", "englishSentence": "The bank is across the street.", "turkishSentence": "Banka sokağın karşısında." },
    { "english": "Below", "turkish": "Aşağıda / Altında", "englishSentence": "The temperature is below zero.", "turkishSentence": "Sıcaklık sıfırın altında." },
    { "english": "On", "turkish": "Üzerinde / -de, -da", "englishSentence": "The book is on the desk.", "turkishSentence": "Kitap masanın üzerinde." },
    { "english": "How", "turkish": "Nasıl", "englishSentence": "How do you feel today?", "turkishSentence": "Bugün nasıl hissediyorsun?" },
    { "english": "Each", "turkish": "Her bir", "englishSentence": "Each student received a book.", "turkishSentence": "Her öğrenci bir kitap aldı." },
    { "english": "Behind", "turkish": "Arkasında", "englishSentence": "The car is behind the building.", "turkishSentence": "Araba binanın arkasında." },
    { "english": "None", "turkish": "Hiçbiri", "englishSentence": "None of them came to the party.", "turkishSentence": "Hiçbiri partiye gelmedi." },
    { "english": "We", "turkish": "Biz", "englishSentence": "We are going to the park.", "turkishSentence": "Parka gidiyoruz." },
    { "english": "Other", "turkish": "Diğer / Başka", "englishSentence": "Do you have any other questions?", "turkishSentence": "Başka sorunuz var mı?" },
    { "english": "Under", "turkish": "Altında", "englishSentence": "The cat is under the table.", "turkishSentence": "Kedi masanın altında." },
    { "english": "Million", "turkish": "Milyon", "englishSentence": "The city has a million people.", "turkishSentence": "Şehirde bir milyon insan yaşıyor." },
    { "english": "Nor", "turkish": "Ne de", "englishSentence": "Neither he nor she was there.", "turkishSentence": "Ne o ne de o oradaydı." },
    { "english": "They", "turkish": "Onlar", "englishSentence": "They are coming tomorrow.", "turkishSentence": "Onlar yarın geliyorlar." },
    { "english": "Could", "turkish": "-ebilirdi / -abilir miydi", "englishSentence": "Could you help me, please?", "turkishSentence": "Bana yardım edebilir misiniz?" },
    { "english": "Away", "turkish": "Uzakta / Uzağa", "englishSentence": "The beach is far away.", "turkishSentence": "Plaj çok uzakta." },
    { "english": "Outside", "turkish": "Dışarıda / Dışında", "englishSentence": "The children are playing outside.", "turkishSentence": "Çocuklar dışarıda oynuyor." },
    { "english": "More", "turkish": "Daha fazla", "englishSentence": "I need more time.", "turkishSentence": "Daha fazla zamana ihtiyacım var." },
    { "english": "Be", "turkish": "Olmak", "englishSentence": "I want to be a doctor.", "turkishSentence": "Doktor olmak istiyorum." },
    { "english": "Our", "turkish": "Bizim", "englishSentence": "This is our house.", "turkishSentence": "Bu bizim evimiz." },
    { "english": "Every", "turkish": "Her", "englishSentence": "I exercise every morning.", "turkishSentence": "Her sabah egzersiz yapıyorum." },
    { "english": "Nine", "turkish": "Dokuz", "englishSentence": "She has nine cats.", "turkishSentence": "Onun dokuz kedisi var." },
    { "english": "Most", "turkish": "En çok / Çoğu", "englishSentence": "Most people like chocolate.", "turkishSentence": "Çoğu insan çikolatayı sever." },
    { "english": "With", "turkish": "İle / Birlikte", "englishSentence": "Come with me.", "turkishSentence": "Benimle gel." },
    { "english": "Into", "turkish": "İçine", "englishSentence": "She walked into the room.", "turkishSentence": "Odanın içine yürüdü." },
    { "english": "Next", "turkish": "Sonraki / Yanındaki", "englishSentence": "The next bus is at ten.", "turkishSentence": "Sonraki otobüs onda." },
    { "english": "Thousand", "turkish": "Bin", "englishSentence": "A thousand people attended.", "turkishSentence": "Bin kişi katıldı." },
    { "english": "This", "turkish": "Bu", "englishSentence": "This is my favorite book.", "turkishSentence": "Bu benim en sevdiğim kitap." },
    { "english": "These", "turkish": "Bunlar", "englishSentence": "These are my friends.", "turkishSentence": "Bunlar benim arkadaşlarım." },
    { "english": "Anything", "turkish": "Herhangi bir şey", "englishSentence": "Is there anything I can do?", "turkishSentence": "Yapabileceğim bir şey var mı?" },
    { "english": "Shall", "turkish": "-ecek (resmi gelecek zaman)", "englishSentence": "Shall we go now?", "turkishSentence": "Şimdi gidelim mi?" },
    { "english": "Have", "turkish": "Sahip olmak / -mek", "englishSentence": "I have a new car.", "turkishSentence": "Yeni bir arabam var." },
    { "english": "Than", "turkish": "-den daha", "englishSentence": "She is taller than me.", "turkishSentence": "O benden uzun." },
    { "english": "Few", "turkish": "Az / Birkaç", "englishSentence": "Only a few people came.", "turkishSentence": "Sadece birkaç kişi geldi." },
    { "english": "Myself", "turkish": "Kendim", "englishSentence": "I did it myself.", "turkishSentence": "Onu kendim yaptım." },
    { "english": "But", "turkish": "Ama / Fakat", "englishSentence": "I like coffee, but not tea.", "turkishSentence": "Kahveyi severim ama çayı sevmem." },
    { "english": "Any", "turkish": "Herhangi / Hiç", "englishSentence": "Do you have any questions?", "turkishSentence": "Hiç sorunuz var mı?" },
    { "english": "Though", "turkish": "Rağmen / Yine de", "englishSentence": "Though tired, he kept working.", "turkishSentence": "Yorgun olmasına rağmen çalışmaya devam etti." },
    { "english": "Themselves", "turkish": "Kendileri", "englishSentence": "They built the house themselves.", "turkishSentence": "Evi kendileri inşa ettiler." },
    { "english": "As", "turkish": "Gibi / Olarak / -ken", "englishSentence": "She works as a teacher.", "turkishSentence": "Öğretmen olarak çalışır." },
    { "english": "Where", "turkish": "Nerede / Nereye", "englishSentence": "Where do you live?", "turkishSentence": "Nerede yaşıyorsun?" },
    { "english": "Since", "turkish": "-den beri / Çünkü", "englishSentence": "I have lived here since 2010.", "turkishSentence": "2010'dan beri burada yaşıyorum." },
    { "english": "Itself", "turkish": "Kendisi (cansız)", "englishSentence": "The problem will fix itself.", "turkishSentence": "Sorun kendiliğinden çözülecek." },
    { "english": "Not", "turkish": "Değil / -me, -ma", "englishSentence": "I am not ready yet.", "turkishSentence": "Henüz hazır değilim." },
    { "english": "Over", "turkish": "Üzerinde / Bitmiş", "englishSentence": "The game is over.", "turkishSentence": "Oyun bitti." },
    { "english": "Against", "turkish": "Karşı / Aleyhinde", "englishSentence": "He is against the idea.", "turkishSentence": "O fikre karşı." },
    { "english": "Somebody", "turkish": "Birisi", "englishSentence": "Somebody is at the door.", "turkishSentence": "Kapıda birisi var." },
    { "english": "At", "turkish": "-de / -da (yer, zaman)", "englishSentence": "I am at school.", "turkishSentence": "Okuldayım." },
    { "english": "Back", "turkish": "Geri / Arka", "englishSentence": "I will be back soon.", "turkishSentence": "Yakında döneceğim." },
    { "english": "Second", "turkish": "İkinci / Saniye", "englishSentence": "This is my second chance.", "turkishSentence": "Bu benim ikinci şansım." },
    { "english": "Upon", "turkish": "Üzerine / -de", "englishSentence": "Once upon a time, there was a king.", "turkishSentence": "Bir zamanlar bir kral vardı." },
    { "english": "What", "turkish": "Ne", "englishSentence": "What do you want?", "turkishSentence": "Ne istiyorsun?" },
    { "english": "First", "turkish": "İlk / Birinci", "englishSentence": "This is my first day.", "turkishSentence": "Bu benim ilk günüm." },
    { "english": "Nothing", "turkish": "Hiçbir şey", "englishSentence": "There is nothing to worry about.", "turkishSentence": "Endişelenecek hiçbir şey yok." },
    { "english": "Thirty", "turkish": "Otuz", "englishSentence": "He is thirty years old.", "turkishSentence": "O otuz yaşında." },
    { "english": "So", "turkish": "Çok / Yani / Bu yüzden", "englishSentence": "I was so tired that I fell asleep.", "turkishSentence": "O kadar yorgundum ki uyuyakaldım." },
    { "english": "Much", "turkish": "Çok (sayılamayan)", "englishSentence": "I don't have much time.", "turkishSentence": "Çok zamanım yok." },
    { "english": "Without", "turkish": "Olmadan / -sız, -siz", "englishSentence": "I can't live without music.", "turkishSentence": "Müziksiz yaşayamam." },
    { "english": "Third", "turkish": "Üçüncü", "englishSentence": "She finished in third place.", "turkishSentence": "Üçüncü sırada bitirdi." },
    { "english": "There", "turkish": "Orada / Oraya", "englishSentence": "I have never been there.", "turkishSentence": "Oraya hiç gitmedim." },
    { "english": "Down", "turkish": "Aşağı / Aşağıda", "englishSentence": "Sit down, please.", "turkishSentence": "Lütfen oturun." },
    { "english": "During", "turkish": "Sırasında / Boyunca", "englishSentence": "It rained during the match.", "turkishSentence": "Maç sırasında yağmur yağdı." },
    { "english": "Above", "turkish": "Üstünde / Yukarısında", "englishSentence": "The plane flew above the clouds.", "turkishSentence": "Uçak bulutların üstünde uçtu." },
    { "english": "Or", "turkish": "Veya / Ya da", "englishSentence": "Do you want tea or coffee?", "turkishSentence": "Çay mı yoksa kahve mi istersin?" },
    { "english": "Its", "turkish": "Onun (cansız)", "englishSentence": "The dog wagged its tail.", "turkishSentence": "Köpek kuyruğunu salladı." },
    { "english": "Six", "turkish": "Altı", "englishSentence": "I wake up at six every day.", "turkishSentence": "Her gün altıda uyanırım." },
    { "english": "Therefore", "turkish": "Bu nedenle / Dolayısıyla", "englishSentence": "He was late; therefore, he missed the bus.", "turkishSentence": "Geç kaldı; bu nedenle otobüsü kaçırdı." },
    { "english": "One", "turkish": "Bir / Kişi", "englishSentence": "One should always be honest.", "turkishSentence": "Kişi her zaman dürüst olmalı." },
    { "english": "Should", "turkish": "-meli / -malı", "englishSentence": "You should eat healthier.", "turkishSentence": "Daha sağlıklı yemelisin." },
    { "english": "Enough", "turkish": "Yeterli / Yeterince", "englishSentence": "I have enough money.", "turkishSentence": "Yeterli param var." },
    { "english": "Everybody", "turkish": "Herkes", "englishSentence": "Everybody likes music.", "turkishSentence": "Herkes müziği sever." },
    { "english": "By", "turkish": "Tarafından / Yanında", "englishSentence": "The book was written by her.", "turkishSentence": "Kitap onun tarafından yazıldı." },
    { "english": "After", "turkish": "Sonra / -den sonra", "englishSentence": "I will go home after work.", "turkishSentence": "İşten sonra eve gideceğim." },
    { "english": "Once", "turkish": "Bir kez / Bir zamanlar", "englishSentence": "I visit my parents once a week.", "turkishSentence": "Ailemi haftada bir ziyaret ederim." },
    { "english": "Towards", "turkish": "Doğru / -e doğru", "englishSentence": "He walked towards the exit.", "turkishSentence": "Çıkışa doğru yürüdü." },
    { "english": "From", "turkish": "-den, -dan", "englishSentence": "I am from Turkey.", "turkishSentence": "Türkiye'denim." },
    { "english": "Those", "turkish": "Şunlar / Onlar", "englishSentence": "Those shoes are expensive.", "turkishSentence": "Şu ayakkabılar pahalı." },
    { "english": "However", "turkish": "Ancak / Bununla birlikte", "englishSentence": "However, he did not give up.", "turkishSentence": "Ancak o vazgeçmedi." },
    { "english": "Thus", "turkish": "Böylece / Bu şekilde", "englishSentence": "He worked hard, thus he succeeded.", "turkishSentence": "Çok çalıştı, böylece başardı." },
    { "english": "All", "turkish": "Hepsi / Tüm", "englishSentence": "All students passed the exam.", "turkishSentence": "Tüm öğrenciler sınavı geçti." },
    { "english": "May", "turkish": "-ebilir / Olabilir", "englishSentence": "May I ask you a question?", "turkishSentence": "Size bir soru sorabilir miyim?" },
    { "english": "Half", "turkish": "Yarım / Yarı", "englishSentence": "I ate half of the cake.", "turkishSentence": "Pastanın yarısını yedim." },
    { "english": "Everyone", "turkish": "Herkes", "englishSentence": "Everyone deserves respect.", "turkishSentence": "Herkes saygıyı hak eder." },
    { "english": "She", "turkish": "O (kadın)", "englishSentence": "She is a talented artist.", "turkishSentence": "O yetenekli bir sanatçı." },
    { "english": "Something", "turkish": "Bir şey", "englishSentence": "I want to tell you something.", "turkishSentence": "Sana bir şey söylemek istiyorum." },
    { "english": "Yet", "turkish": "Henüz / Hâlâ", "englishSentence": "I haven't finished yet.", "turkishSentence": "Henüz bitirmedim." },
    { "english": "Near", "turkish": "Yakın / Yakınında", "englishSentence": "The school is near our house.", "turkishSentence": "Okul evimizin yakınında." },
    { "english": "No", "turkish": "Hayır / Hiç", "englishSentence": "No, I don't agree.", "turkishSentence": "Hayır, katılmıyorum." },
    { "english": "Three", "turkish": "Üç", "englishSentence": "I have three sisters.", "turkishSentence": "Üç kız kardeşim var." },
    { "english": "Whether", "turkish": "Olup olmadığı / -ip -meyeceği", "englishSentence": "I don't know whether he will come.", "turkishSentence": "Gelip gelmeyeceğini bilmiyorum." },
    { "english": "Inside", "turkish": "İçeride / İçinde", "englishSentence": "Please come inside.", "turkishSentence": "Lütfen içeri gelin." },
    { "english": "His", "turkish": "Onun (erkek)", "englishSentence": "His car is blue.", "turkishSentence": "Onun arabası mavi." },
    { "english": "Little", "turkish": "Küçük / Az", "englishSentence": "She has a little dog.", "turkishSentence": "Onun küçük bir köpeği var." },
    { "english": "Everything", "turkish": "Her şey", "englishSentence": "Everything will be alright.", "turkishSentence": "Her şey iyi olacak." },
    { "english": "Nineteen", "turkish": "On dokuz", "englishSentence": "She is nineteen years old.", "turkishSentence": "O on dokuz yaşında." },
    { "english": "Do", "turkish": "Yapmak", "englishSentence": "What do you do for a living?", "turkishSentence": "Geçimin için ne yapıyorsun?" },
    { "english": "Many", "turkish": "Birçok / Çok", "englishSentence": "Many students like sports.", "turkishSentence": "Birçok öğrenci sporu sever." },
    { "english": "Until", "turkish": "-e kadar", "englishSentence": "Wait until the light turns green.", "turkishSentence": "Işık yeşile dönene kadar bekle." },
    { "english": "Yourself", "turkish": "Kendin", "englishSentence": "You should do it yourself.", "turkishSentence": "Bunu kendin yapmalısın." },
    { "english": "Can", "turkish": "-ebilmek / Yapabilmek", "englishSentence": "Can you speak English?", "turkishSentence": "İngilizce konuşabiliyor musun?" },
    { "english": "Why", "turkish": "Neden / Niçin", "englishSentence": "Why are you late?", "turkishSentence": "Neden geç kaldın?" },
    { "english": "Hundred", "turkish": "Yüz", "englishSentence": "There were a hundred people.", "turkishSentence": "Yüz kişi vardı." },
    { "english": "Fifty", "turkish": "Elli", "englishSentence": "He has fifty employees.", "turkishSentence": "Onun elli çalışanı var." },
    { "english": "If", "turkish": "Eğer / -se, -sa", "englishSentence": "If it rains, we will stay home.", "turkishSentence": "Eğer yağmur yağarsa evde kalırız." },
    { "english": "Before", "turkish": "Önce / -den önce", "englishSentence": "Wash your hands before eating.", "turkishSentence": "Yemekten önce ellerini yıka." },
    { "english": "Within", "turkish": "İçinde / Dahilinde", "englishSentence": "The answer is within yourself.", "turkishSentence": "Cevap senin içinde." },
    { "english": "Whose", "turkish": "Kimin", "englishSentence": "Whose bag is this?", "turkishSentence": "Bu kimin çantası?" },
    { "english": "About", "turkish": "Hakkında / Yaklaşık", "englishSentence": "Tell me about yourself.", "turkishSentence": "Kendinden bahset." },
    { "english": "Such", "turkish": "Böyle / Öyle", "englishSentence": "Such things happen sometimes.", "turkishSentence": "Böyle şeyler bazen olur." },
    { "english": "Ten", "turkish": "On", "englishSentence": "I have ten fingers.", "turkishSentence": "On parmağım var." },
    { "english": "Anyone", "turkish": "Herhangi biri / Kimse", "englishSentence": "Does anyone know the answer?", "turkishSentence": "Cevabı bilen var mı?" },
    { "english": "My", "turkish": "Benim", "englishSentence": "This is my house.", "turkishSentence": "Bu benim evim." },
    { "english": "Off", "turkish": "Kapalı / Uzakta", "englishSentence": "Please turn off the lights.", "turkishSentence": "Lütfen ışıkları kapat." },
    { "english": "Twenty", "turkish": "Yirmi", "englishSentence": "I am twenty years old.", "turkishSentence": "Yirmi yaşındayım." },
    { "english": "Per", "turkish": "Başına / Her bir", "englishSentence": "It costs ten dollars per person.", "turkishSentence": "Kişi başına on dolara mal oluyor." },
    { "english": "Her", "turkish": "Onun (kadın) / Onu", "englishSentence": "I gave her a gift.", "turkishSentence": "Ona bir hediye verdim." },
    { "english": "Through", "turkish": "Boyunca / İçinden", "englishSentence": "We drove through the tunnel.", "turkishSentence": "Tünelden geçtik." },
    { "english": "Either", "turkish": "Ya ... ya da / Her ikisi", "englishSentence": "Either you or I will go.", "turkishSentence": "Ya sen ya da ben gideceğiz." },
    { "english": "Except", "turkish": "Hariç / -den başka", "englishSentence": "Everyone came except John.", "turkishSentence": "John hariç herkes geldi." }
];
