// BBC 800 Essential Words - Part 6 (Sub-list 11-12)
const wordsPart6 = [
    // Sub-list 11
    { "english": "Approach", "turkish": "Yaklaşım / Yaklaşmak", "englishSentence": "We need a different approach.", "turkishSentence": "Farklı bir yaklaşıma ihtiyacımız var." },
    { "english": "Pressure", "turkish": "Baskı / Basınç", "englishSentence": "She works well under pressure.", "turkishSentence": "Baskı altında iyi çalışır." },
    { "english": "Island", "turkish": "Ada", "englishSentence": "They live on a small island.", "turkishSentence": "Küçük bir adada yaşıyorlar." },
    { "english": "Fish", "turkish": "Balık", "englishSentence": "I had fish for dinner.", "turkishSentence": "Akşam yemeğinde balık yedim." },
    { "english": "Cover", "turkish": "Kapak / Örtmek / Kaplamak", "englishSentence": "Cover the pot with a lid.", "turkishSentence": "Tencereyi kapakla ört." },
    { "english": "Computer", "turkish": "Bilgisayar", "englishSentence": "I use a computer every day.", "turkishSentence": "Her gün bilgisayar kullanırım." },
    { "english": "Picture", "turkish": "Resim / Fotoğraf", "englishSentence": "Let me take a picture.", "turkishSentence": "Bir fotoğraf çekeyim." },
    { "english": "Sign", "turkish": "İşaret / İmzalamak", "englishSentence": "Please sign here.", "turkishSentence": "Lütfen buraya imza atın." },
    { "english": "Clearly", "turkish": "Açıkça / Net bir şekilde", "englishSentence": "She spoke clearly.", "turkishSentence": "Net bir şekilde konuştu." },
    { "english": "Afternoon", "turkish": "Öğleden sonra", "englishSentence": "I'll be free in the afternoon.", "turkishSentence": "Öğleden sonra müsait olacağım." },
    { "english": "Straight", "turkish": "Düz / Doğruca", "englishSentence": "Go straight ahead.", "turkishSentence": "Düz ilerleyin." },
    { "english": "Relationship", "turkish": "İlişki", "englishSentence": "They have a good relationship.", "turkishSentence": "İyi bir ilişkileri var." },
    { "english": "Basic", "turkish": "Temel", "englishSentence": "These are the basic rules.", "turkishSentence": "Bunlar temel kurallar." },
    { "english": "Share", "turkish": "Paylaşmak / Pay", "englishSentence": "Let's share this pizza.", "turkishSentence": "Bu pizzayı paylaşalım." },
    { "english": "Science", "turkish": "Bilim", "englishSentence": "Science helps us understand the world.", "turkishSentence": "Bilim dünyayı anlamamıza yardımcı olur." },
    { "english": "Space", "turkish": "Uzay / Alan", "englishSentence": "There isn't enough space here.", "turkishSentence": "Burada yeterli alan yok." },
    { "english": "Dark", "turkish": "Karanlık", "englishSentence": "It gets dark early in winter.", "turkishSentence": "Kışın erken karanlık olur." },
    { "english": "Military", "turkish": "Askeri", "englishSentence": "He served in the military.", "turkishSentence": "Askerde görev yaptı." },
    { "english": "Doubt", "turkish": "Şüphe / Şüphelenmek", "englishSentence": "I have no doubt about it.", "turkishSentence": "Bu konuda hiç şüphem yok." },
    { "english": "Colour", "turkish": "Renk", "englishSentence": "What is your favourite colour?", "turkishSentence": "En sevdiğin renk ne?" },
    { "english": "Drive", "turkish": "Sürmek / Araba kullanmak", "englishSentence": "I can drive a car.", "turkishSentence": "Araba kullanabilirim." },
    { "english": "Press", "turkish": "Basın / Basmak", "englishSentence": "Press the green button.", "turkishSentence": "Yeşil düğmeye bas." },
    { "english": "Wide", "turkish": "Geniş", "englishSentence": "The river is very wide.", "turkishSentence": "Nehir çok geniş." },
    { "english": "Expect", "turkish": "Beklemek / Ummak", "englishSentence": "I didn't expect this result.", "turkishSentence": "Bu sonucu beklemiyordum." },
    { "english": "Fall", "turkish": "Düşmek / Sonbahar", "englishSentence": "Be careful not to fall.", "turkishSentence": "Düşmemeye dikkat et." },
    { "english": "Visit", "turkish": "Ziyaret etmek", "englishSentence": "I visit my grandmother every week.", "turkishSentence": "Her hafta büyükannemi ziyaret ederim." },
    { "english": "Spend", "turkish": "Harcamak / Geçirmek", "englishSentence": "Don't spend too much money.", "turkishSentence": "Çok fazla para harcama." },
    { "english": "Step", "turkish": "Adım / Basamak", "englishSentence": "Take one step at a time.", "turkishSentence": "Bir seferde bir adım at." },
    { "english": "Capital", "turkish": "Başkent / Sermaye", "englishSentence": "Ankara is the capital of Turkey.", "turkishSentence": "Ankara Türkiye'nin başkentidir." },
    { "english": "Performance", "turkish": "Performans / Gösteri", "englishSentence": "Her performance was amazing.", "turkishSentence": "Performansı harikaydı." },
    { "english": "Green", "turkish": "Yeşil", "englishSentence": "The grass is green.", "turkishSentence": "Çimen yeşildir." },
    { "english": "Consider", "turkish": "Düşünmek / Değerlendirmek", "englishSentence": "Please consider my proposal.", "turkishSentence": "Lütfen teklifimi değerlendirin." },
    { "english": "Income", "turkish": "Gelir", "englishSentence": "His income has doubled.", "turkishSentence": "Geliri iki katına çıktı." },
    { "english": "Culture", "turkish": "Kültür", "englishSentence": "I love learning about different cultures.", "turkishSentence": "Farklı kültürleri öğrenmeyi seviyorum." },
    { "english": "Teaching", "turkish": "Öğretim / Öğretme", "englishSentence": "Teaching is a noble profession.", "turkishSentence": "Öğretmenlik asil bir meslektir." },
    { "english": "Sea", "turkish": "Deniz", "englishSentence": "The sea is calm today.", "turkishSentence": "Bugün deniz sakin." },
    { "english": "Drink", "turkish": "İçmek / İçecek", "englishSentence": "Would you like a drink?", "turkishSentence": "Bir içecek ister misiniz?" },
    { "english": "Pick", "turkish": "Seçmek / Toplamak", "englishSentence": "Pick a card, any card.", "turkishSentence": "Bir kart seç, herhangi bir kart." },
    { "english": "Hotel", "turkish": "Otel", "englishSentence": "We stayed at a nice hotel.", "turkishSentence": "Güzel bir otelde kaldık." },
    { "english": "River", "turkish": "Nehir", "englishSentence": "We swam in the river.", "turkishSentence": "Nehirde yüzdük." },
    { "english": "Truth", "turkish": "Gerçek / Doğruluk", "englishSentence": "Tell me the truth.", "turkishSentence": "Bana gerçeği söyle." },
    { "english": "Complete", "turkish": "Tamamlamak / Tam", "englishSentence": "Please complete the form.", "turkishSentence": "Lütfen formu tamamlayın." },
    { "english": "Bye", "turkish": "Hoşça kal", "englishSentence": "Bye, see you later!", "turkishSentence": "Hoşça kal, sonra görüşürüz!" },
    { "english": "Authority", "turkish": "Otorite / Yetki", "englishSentence": "He has the authority to decide.", "turkishSentence": "Karar verme yetkisine sahip." },
    { "english": "Film", "turkish": "Film", "englishSentence": "I watched a great film last night.", "turkishSentence": "Dün gece harika bir film izledim." },
    { "english": "Movement", "turkish": "Hareket / Akım", "englishSentence": "The movement grew quickly.", "turkishSentence": "Akım hızla büyüdü." },
    { "english": "Economy", "turkish": "Ekonomi", "englishSentence": "The economy is recovering.", "turkishSentence": "Ekonomi toparlanıyor." },
    { "english": "Christmas", "turkish": "Noel", "englishSentence": "Merry Christmas!", "turkishSentence": "Mutlu Noeller!" },
    { "english": "Fast", "turkish": "Hızlı", "englishSentence": "He runs very fast.", "turkishSentence": "Çok hızlı koşuyor." },
    { "english": "Continue", "turkish": "Devam etmek", "englishSentence": "Please continue reading.", "turkishSentence": "Lütfen okumaya devam edin." },

    // Sub-list 12
    { "english": "Kill", "turkish": "Öldürmek", "englishSentence": "Smoking can kill.", "turkishSentence": "Sigara öldürebilir." },
    { "english": "Design", "turkish": "Tasarım / Tasarlamak", "englishSentence": "I like the design of this building.", "turkishSentence": "Bu binanın tasarımını beğeniyorum." },
    { "english": "Follow", "turkish": "Takip etmek / İzlemek", "englishSentence": "Follow me, please.", "turkishSentence": "Lütfen beni takip edin." },
    { "english": "Wonder", "turkish": "Merak etmek / Harika", "englishSentence": "I wonder what will happen.", "turkishSentence": "Ne olacağını merak ediyorum." },
    { "english": "Theory", "turkish": "Teori / Kuram", "englishSentence": "In theory, it should work.", "turkishSentence": "Teoride işe yaramalı." },
    { "english": "Shot", "turkish": "Atış / Vuruş / Deneme", "englishSentence": "He took a shot at the goal.", "turkishSentence": "Kaleye bir şut attı." },
    { "english": "Worry", "turkish": "Endişe / Endişelenmek", "englishSentence": "Don't worry about it.", "turkishSentence": "Endişelenme." },
    { "english": "Function", "turkish": "İşlev / Fonksiyon", "englishSentence": "What is the function of this device?", "turkishSentence": "Bu cihazın işlevi ne?" },
    { "english": "Dinner", "turkish": "Akşam yemeği", "englishSentence": "What's for dinner tonight?", "turkishSentence": "Bu akşam yemekte ne var?" },
    { "english": "Practice", "turkish": "Pratik / Uygulama", "englishSentence": "Practice makes perfect.", "turkishSentence": "Pratik mükemmelleştirir." },
    { "english": "Medical", "turkish": "Tıbbi", "englishSentence": "He needs medical attention.", "turkishSentence": "Tıbbi müdahaleye ihtiyacı var." },
    { "english": "Energy", "turkish": "Enerji", "englishSentence": "I don't have enough energy today.", "turkishSentence": "Bugün yeterli enerjim yok." },
    { "english": "Offer", "turkish": "Teklif / Sunmak", "englishSentence": "I received a job offer.", "turkishSentence": "Bir iş teklifi aldım." },
    { "english": "Generally", "turkish": "Genellikle", "englishSentence": "I am generally a calm person.", "turkishSentence": "Genellikle sakin bir insanımdır." },
    { "english": "Page", "turkish": "Sayfa", "englishSentence": "Turn to page ten.", "turkishSentence": "Onuncu sayfaya çevir." },
    { "english": "Former", "turkish": "Eski / Önceki", "englishSentence": "He is the former president.", "turkishSentence": "O eski cumhurbaşkanı." },
    { "english": "Fair", "turkish": "Adil / Fuar", "englishSentence": "That's not fair!", "turkishSentence": "Bu adil değil!" },
    { "english": "Patients", "turkish": "Hastalar", "englishSentence": "The doctor sees many patients.", "turkishSentence": "Doktor birçok hasta görüyor." },
    { "english": "Average", "turkish": "Ortalama", "englishSentence": "The average temperature is 20 degrees.", "turkishSentence": "Ortalama sıcaklık 20 derece." },
    { "english": "Sister", "turkish": "Kız kardeş / Abla", "englishSentence": "My sister lives abroad.", "turkishSentence": "Kız kardeşim yurt dışında yaşıyor." },
    { "english": "Radio", "turkish": "Radyo", "englishSentence": "I listen to the radio every morning.", "turkishSentence": "Her sabah radyo dinlerim." },
    { "english": "Significant", "turkish": "Önemli / Anlamlı", "englishSentence": "This is a significant change.", "turkishSentence": "Bu önemli bir değişiklik." },
    { "english": "Respect", "turkish": "Saygı / Saygı duymak", "englishSentence": "We should respect each other.", "turkishSentence": "Birbirimize saygı duymalıyız." },
    { "english": "Absolutely", "turkish": "Kesinlikle", "englishSentence": "Absolutely, I agree with you.", "turkishSentence": "Kesinlikle, sana katılıyorum." },
    { "english": "Legal", "turkish": "Yasal / Hukuki", "englishSentence": "Is this legal?", "turkishSentence": "Bu yasal mı?" },
    { "english": "Deep", "turkish": "Derin", "englishSentence": "The pool is very deep.", "turkishSentence": "Havuz çok derin." },
    { "english": "Structure", "turkish": "Yapı", "englishSentence": "The structure of the building is solid.", "turkishSentence": "Binanın yapısı sağlam." },
    { "english": "Somewhere", "turkish": "Bir yerde", "englishSentence": "I left my keys somewhere.", "turkishSentence": "Anahtarlarımı bir yere bıraktım." },
    { "english": "Pass", "turkish": "Geçmek / Pas vermek", "englishSentence": "Please pass the salt.", "turkishSentence": "Lütfen tuzu uzat." },
    { "english": "Begin", "turkish": "Başlamak", "englishSentence": "Let's begin the lesson.", "turkishSentence": "Derse başlayalım." },
    { "english": "Club", "turkish": "Kulüp", "englishSentence": "She joined a sports club.", "turkishSentence": "Bir spor kulübüne katıldı." },
    { "english": "Include", "turkish": "Dahil etmek / İçermek", "englishSentence": "The price includes breakfast.", "turkishSentence": "Fiyata kahvaltı dahil." },
    { "english": "Nearly", "turkish": "Neredeyse / Hemen hemen", "englishSentence": "It's nearly time to go.", "turkishSentence": "Gitme zamanı neredeyse geldi." },
    { "english": "Quickly", "turkish": "Hızlıca / Çabucak", "englishSentence": "He finished his work quickly.", "turkishSentence": "İşini çabucak bitirdi." },
    { "english": "Purpose", "turkish": "Amaç", "englishSentence": "What is the purpose of this meeting?", "turkishSentence": "Bu toplantının amacı ne?" },
    { "english": "Sunday", "turkish": "Pazar", "englishSentence": "We usually rest on Sunday.", "turkishSentence": "Genellikle pazar günü dinleniriz." },
    { "english": "Daughter", "turkish": "Kız evlat", "englishSentence": "My daughter loves reading.", "turkishSentence": "Kızım okumayı çok seviyor." },
    { "english": "Charge", "turkish": "Ücret / Suçlama / Şarj", "englishSentence": "There is no extra charge.", "turkishSentence": "Ekstra ücret yok." },
    { "english": "Specific", "turkish": "Belirli / Spesifik", "englishSentence": "Can you be more specific?", "turkishSentence": "Daha spesifik olabilir misin?" },
    { "english": "Completely", "turkish": "Tamamen", "englishSentence": "I completely agree.", "turkishSentence": "Tamamen katılıyorum." },
    { "english": "Earth", "turkish": "Dünya / Toprak", "englishSentence": "The earth goes around the sun.", "turkishSentence": "Dünya güneşin etrafında döner." },
    { "english": "Organisation", "turkish": "Kuruluş / Örgüt", "englishSentence": "She works for a charity organisation.", "turkishSentence": "Bir hayır kuruluşunda çalışıyor." },
    { "english": "Wall", "turkish": "Duvar", "englishSentence": "There is a painting on the wall.", "turkishSentence": "Duvarda bir tablo var." },
    { "english": "Property", "turkish": "Mülk / Özellik", "englishSentence": "This property is for sale.", "turkishSentence": "Bu mülk satılıktır." },
    { "english": "Activity", "turkish": "Aktivite / Faaliyet", "englishSentence": "Physical activity is important.", "turkishSentence": "Fiziksel aktivite önemlidir." },
    { "english": "Note", "turkish": "Not / Nota", "englishSentence": "Please take note of this.", "turkishSentence": "Lütfen bunu not edin." },
    { "english": "Treatment", "turkish": "Tedavi / Muamele", "englishSentence": "The treatment was successful.", "turkishSentence": "Tedavi başarılı oldu." },
    { "english": "Station", "turkish": "İstasyon", "englishSentence": "The train station is nearby.", "turkishSentence": "Tren istasyonu yakında." },
    { "english": "Teacher", "turkish": "Öğretmen", "englishSentence": "She is a wonderful teacher.", "turkishSentence": "O harika bir öğretmen." },
    { "english": "Forget", "turkish": "Unutmak", "englishSentence": "Don't forget to call me.", "turkishSentence": "Beni aramayı unutma." }
];
