// BBC 800 Essential Words - BlitzFlash Vocabulary Database
// This file combines all word parts with Turkish translations

const vocabulary = [
    // Base list (already in system)
    { "english": "The", "turkish": "Belirli bir nesneyi işaret eden takı", "englishSentence": "The book on the table is mine.", "turkishSentence": "Masadaki kitap benimdir." },
    { "english": "Which", "turkish": "Hangi / Hangisi", "englishSentence": "Which color do you prefer?", "turkishSentence": "Hangi rengi tercih edersin?" },
    { "english": "Still", "turkish": "Hâlâ / Yine de", "englishSentence": "It is late, but he is still working.", "turkishSentence": "Vakit geç oldu ama o hâlâ çalışıyor." },
    { "english": "Although", "turkish": "Rağmen / Karşın", "englishSentence": "Although it was raining, they went for a walk.", "turkishSentence": "Yağmur yağmasına rağmen yürüyüşe çıktılar." },
    { "english": "And", "turkish": "Ve", "englishSentence": "I bought apples and oranges.", "turkishSentence": "Elma ve portakal satın aldım." },
    { "english": "Up", "turkish": "Yukarı / Yukarıya", "englishSentence": "Please look up at the stars.", "turkishSentence": "Lütfen yukarıdaki yıldızlara bak." },
    { "english": "Of", "turkish": "-ın, -in eki / Parçası", "englishSentence": "The roof of the house is red.", "turkishSentence": "Evin çatısı kırmızıdır." },
    { "english": "Out", "turkish": "Dışarı / Dışarıda", "englishSentence": "Let's go out for dinner tonight.", "turkishSentence": "Bu gece akşam yemeği için dışarı çıkalım." },
    { "english": "To", "turkish": "-e, -a yönelme eki", "englishSentence": "I am going to the office now.", "turkishSentence": "Şimdi ofise gidiyorum." },
    { "english": "When", "turkish": "Ne zaman", "englishSentence": "When will the meeting start?", "turkishSentence": "Toplantı ne zaman başlayacak?" },
    { "english": "Know", "turkish": "Bilmek / Tanımak", "englishSentence": "I know the answer.", "turkishSentence": "Cevabı biliyorum." },
    { "english": "Go", "turkish": "Gitmek", "englishSentence": "We should go to the park.", "turkishSentence": "Parka gitmeliyiz." },
    { "english": "Like", "turkish": "Sevmek / Gibi", "englishSentence": "I like drinking coffee.", "turkishSentence": "Kahve içmeyi severim." },
    { "english": "Come", "turkish": "Gelmek", "englishSentence": "Please come inside.", "turkishSentence": "Lütfen içeri gel." },
    { "english": "Make", "turkish": "Yapmak / Etmek", "englishSentence": "She can make delicious cakes.", "turkishSentence": "O lezzetli kekler yapabilir." },
    { "english": "Think", "turkish": "Düşünmek", "englishSentence": "I think it's going to rain.", "turkishSentence": "Bence yağmur yağacak." },
    { "english": "People", "turkish": "İnsanlar", "englishSentence": "There were many people.", "turkishSentence": "Çok fazla insan vardı." },
    { "english": "Want", "turkish": "İstemek", "englishSentence": "I want to buy a new car.", "turkishSentence": "Yeni bir araba almak istiyorum." },
    { "english": "Right", "turkish": "Doğru / Sağ / Hak", "englishSentence": "You are right about this.", "turkishSentence": "Bu konuda haklısın." },
    { "english": "Here", "turkish": "Burada / Buraya", "englishSentence": "Please wait for me here.", "turkishSentence": "Lütfen burada beni bekle." },
    { "english": "Way", "turkish": "Yol / Yöntem", "englishSentence": "Is this the right way?", "turkishSentence": "Doğru yol bu mu?" },
    { "english": "Good", "turkish": "İyi / Güzel", "englishSentence": "This is a very good movie.", "turkishSentence": "Bu çok iyi bir film." },
    { "english": "Now", "turkish": "Şimdi / Şu an", "englishSentence": "I am busy right now.", "turkishSentence": "Şu an meşgulüm." },
    { "english": "Get", "turkish": "Almak / Elde etmek", "englishSentence": "Can you get some milk?", "turkishSentence": "Biraz süt alabilir misin?" },
    { "english": "Time", "turkish": "Zaman / Vakit", "englishSentence": "Time flies when having fun.", "turkishSentence": "Eğlenirken zaman uçup gidiyor." },
    { "english": "Say", "turkish": "Söylemek / Demek", "englishSentence": "What did you say?", "turkishSentence": "Ne söyledin?" },
    { "english": "Work", "turkish": "Çalışmak / İş", "englishSentence": "I have a lot of work.", "turkishSentence": "Çok işim var." },
    // Sub-list 1
    { "english": "Again", "turkish": "Tekrar / Yeniden", "englishSentence": "Please say that again.", "turkishSentence": "Lütfen bunu tekrar söyle." },
    { "english": "Own", "turkish": "Kendi / Sahip olmak", "englishSentence": "I have my own car.", "turkishSentence": "Kendi arabam var." },
    { "english": "Quite", "turkish": "Oldukça / Epey", "englishSentence": "The movie was quite interesting.", "turkishSentence": "Film oldukça ilginçti." },
    { "english": "Give", "turkish": "Vermek", "englishSentence": "Can you give me some water?", "turkishSentence": "Bana biraz su verebilir misin?" },
    { "english": "Home", "turkish": "Ev / Yuva", "englishSentence": "I want to go home.", "turkishSentence": "Eve gitmek istiyorum." },
    { "english": "Tell", "turkish": "Söylemek / Anlatmak", "englishSentence": "Tell me the truth.", "turkishSentence": "Bana doğruyu söyle." },
    { "english": "World", "turkish": "Dünya", "englishSentence": "The world is a beautiful place.", "turkishSentence": "Dünya güzel bir yer." },
    { "english": "Use", "turkish": "Kullanmak", "englishSentence": "Can I use your phone?", "turkishSentence": "Telefonunu kullanabilir miyim?" },
    { "english": "Always", "turkish": "Her zaman / Daima", "englishSentence": "She always wakes up early.", "turkishSentence": "O her zaman erken kalkar." },
    { "english": "Great", "turkish": "Harika / Büyük", "englishSentence": "That's a great idea!", "turkishSentence": "Bu harika bir fikir!" },
    { "english": "Kind", "turkish": "Tür / Nazik", "englishSentence": "What kind of music do you like?", "turkishSentence": "Ne tür müzik seversin?" },
    { "english": "Actually", "turkish": "Aslında", "englishSentence": "Actually, I changed my mind.", "turkishSentence": "Aslında fikrimi değiştirdim." },
    { "english": "Sort", "turkish": "Tür / Çeşit", "englishSentence": "What sort of food is this?", "turkishSentence": "Bu ne tür bir yemek?" },
    { "english": "Government", "turkish": "Hükümet", "englishSentence": "The government announced new rules.", "turkishSentence": "Hükümet yeni kurallar açıkladı." },
    { "english": "House", "turkish": "Ev", "englishSentence": "They bought a new house.", "turkishSentence": "Yeni bir ev satın aldılar." },
    { "english": "Find", "turkish": "Bulmak", "englishSentence": "I can't find my keys.", "turkishSentence": "Anahtarlarımı bulamıyorum." },
    { "english": "Different", "turkish": "Farklı", "englishSentence": "We have different opinions.", "turkishSentence": "Farklı görüşlerimiz var." },
    { "english": "Part", "turkish": "Parça / Kısım", "englishSentence": "This is the best part.", "turkishSentence": "En iyi kısım bu." },
    { "english": "Sure", "turkish": "Emin / Tabii ki", "englishSentence": "Are you sure about this?", "turkishSentence": "Bundan emin misin?" },
    { "english": "Bit", "turkish": "Parça / Biraz", "englishSentence": "Wait a bit, I'm coming.", "turkishSentence": "Biraz bekle, geliyorum." },
    // Sub-list 2
    { "english": "Problem", "turkish": "Sorun / Problem", "englishSentence": "There is a problem.", "turkishSentence": "Bir sorun var." },
    { "english": "Love", "turkish": "Sevgi / Aşk / Sevmek", "englishSentence": "I love my family.", "turkishSentence": "Ailemi seviyorum." },
    { "english": "Name", "turkish": "İsim / Ad", "englishSentence": "What is your name?", "turkishSentence": "Adın ne?" },
    { "english": "Percent", "turkish": "Yüzde", "englishSentence": "There is 50 percent chance.", "turkishSentence": "Yüzde 50 ihtimal var." },
    { "english": "Call", "turkish": "Aramak / Çağırmak", "englishSentence": "I will call you tomorrow.", "turkishSentence": "Yarın seni arayacağım." },
    { "english": "Water", "turkish": "Su", "englishSentence": "Drink plenty of water.", "turkishSentence": "Bol su iç." },
    { "english": "Important", "turkish": "Önemli", "englishSentence": "This is very important.", "turkishSentence": "Bu çok önemli." },
    { "english": "Country", "turkish": "Ülke", "englishSentence": "Turkey is a beautiful country.", "turkishSentence": "Türkiye güzel bir ülke." },
    { "english": "Small", "turkish": "Küçük", "englishSentence": "I live in a small apartment.", "turkishSentence": "Küçük bir dairede yaşıyorum." },
    { "english": "Feel", "turkish": "Hissetmek", "englishSentence": "I feel happy today.", "turkishSentence": "Bugün mutlu hissediyorum." },
    { "english": "Real", "turkish": "Gerçek", "englishSentence": "Is this story real?", "turkishSentence": "Bu hikaye gerçek mi?" },
    { "english": "Best", "turkish": "En iyi", "englishSentence": "She is my best friend.", "turkishSentence": "O benim en iyi arkadaşım." },
    { "english": "Laugh", "turkish": "Gülmek", "englishSentence": "He made everyone laugh.", "turkishSentence": "Herkesi güldürdü." },
    { "english": "Remember", "turkish": "Hatırlamak", "englishSentence": "I remember our first meeting.", "turkishSentence": "İlk tanışmamızı hatırlıyorum." },
    { "english": "Less", "turkish": "Daha az", "englishSentence": "Try to eat less sugar.", "turkishSentence": "Daha az şeker yemeye çalış." },
    { "english": "Question", "turkish": "Soru", "englishSentence": "Can I ask a question?", "turkishSentence": "Bir soru sorabilir miyim?" },
    { "english": "Car", "turkish": "Araba", "englishSentence": "He drives a red car.", "turkishSentence": "Kırmızı bir araba kullanıyor." },
    { "english": "Person", "turkish": "Kişi / İnsan", "englishSentence": "She is a kind person.", "turkishSentence": "O nazik bir insan." },
    // Sub-list 3
    { "english": "Later", "turkish": "Sonra / Daha sonra", "englishSentence": "See you later!", "turkishSentence": "Sonra görüşürüz!" },
    { "english": "Sorry", "turkish": "Üzgünüm / Özür dilerim", "englishSentence": "Sorry for being late.", "turkishSentence": "Geç kaldığım için özür dilerim." },
    { "english": "Try", "turkish": "Denemek", "englishSentence": "You should try this food.", "turkishSentence": "Bu yemeği denemelisin." },
    { "english": "Change", "turkish": "Değişim / Değiştirmek", "englishSentence": "Change is always good.", "turkishSentence": "Değişim her zaman iyidir." },
    { "english": "General", "turkish": "Genel", "englishSentence": "In general, people are friendly.", "turkishSentence": "Genel olarak insanlar cana yakın." },
    { "english": "Area", "turkish": "Alan / Bölge", "englishSentence": "This area is very quiet.", "turkishSentence": "Bu bölge çok sessiz." },
    { "english": "Believe", "turkish": "İnanmak", "englishSentence": "I believe in you.", "turkishSentence": "Sana inanıyorum." },
    { "english": "Young", "turkish": "Genç", "englishSentence": "He is still very young.", "turkishSentence": "O hâlâ çok genç." },
    { "english": "Power", "turkish": "Güç / Enerji", "englishSentence": "Knowledge is power.", "turkishSentence": "Bilgi güçtür." },
    { "english": "Almost", "turkish": "Neredeyse", "englishSentence": "I am almost finished.", "turkishSentence": "Neredeyse bitirdim." },
    { "english": "Start", "turkish": "Başlamak", "englishSentence": "Let's start the meeting.", "turkishSentence": "Toplantıya başlayalım." },
    { "english": "Hand", "turkish": "El", "englishSentence": "Raise your hand.", "turkishSentence": "Elini kaldır." },
    { "english": "Show", "turkish": "Göstermek / Gösteri", "englishSentence": "Can you show me the way?", "turkishSentence": "Bana yolu gösterebilir misin?" },
    { "english": "Order", "turkish": "Sipariş / Düzen", "englishSentence": "I would like to order.", "turkishSentence": "Sipariş vermek istiyorum." },
    { "english": "Head", "turkish": "Kafa / Baş", "englishSentence": "I have a headache.", "turkishSentence": "Başım ağrıyor." },
    { "english": "Mind", "turkish": "Akıl / Zihin", "englishSentence": "Keep an open mind.", "turkishSentence": "Açık fikirli ol." },
    { "english": "Together", "turkish": "Birlikte", "englishSentence": "We work together.", "turkishSentence": "Birlikte çalışıyoruz." },
    { "english": "Already", "turkish": "Zaten / Çoktan", "englishSentence": "I have already eaten.", "turkishSentence": "Zaten yedim." },
    { "english": "Able", "turkish": "Yapabilir / Muktedir", "englishSentence": "I am able to help you.", "turkishSentence": "Sana yardım edebilirim." },
    { "english": "Thank", "turkish": "Teşekkür etmek", "englishSentence": "Thank you for your help.", "turkishSentence": "Yardımın için teşekkür ederim." }
];
