// BBC 800 Essential Words - Part 6 (Sub-list 11-13)
const wordsPart6 = [
    // Sub-list 10-11
    { "english": "Trouble", "turkish": "Sorun / Sıkıntı", "englishSentence": "Are you in trouble?", "turkishSentence": "Başın belada mı?" },
    { "english": "Ball", "turkish": "Top", "englishSentence": "Throw the ball.", "turkishSentence": "Topu at." },
    { "english": "Minister", "turkish": "Bakan", "englishSentence": "The minister gave a statement.", "turkishSentence": "Bakan bir açıklama yaptı." },
    { "english": "Ahead", "turkish": "İleri / Önde", "englishSentence": "Go straight ahead.", "turkishSentence": "Düz ileri git." },
    { "english": "Tonight", "turkish": "Bu gece", "englishSentence": "Are you free tonight?", "turkishSentence": "Bu gece müsait misin?" },
    { "english": "Account", "turkish": "Hesap", "englishSentence": "I opened a bank account.", "turkishSentence": "Banka hesabı açtım." },
    { "english": "Size", "turkish": "Boyut / Beden", "englishSentence": "What size do you wear?", "turkishSentence": "Hangi bedeni giyiyorsun?" },
    { "english": "Hot", "turkish": "Sıcak", "englishSentence": "The coffee is too hot.", "turkishSentence": "Kahve çok sıcak." },
    { "english": "Worth", "turkish": "Değer / Değerinde", "englishSentence": "It's worth trying.", "turkishSentence": "Denemeye değer." },
    { "english": "Modern", "turkish": "Modern", "englishSentence": "This is a modern building.", "turkishSentence": "Bu modern bir bina." },
    { "english": "Simple", "turkish": "Basit", "englishSentence": "The answer is simple.", "turkishSentence": "Cevap basit." },
    { "english": "Student", "turkish": "Öğrenci", "englishSentence": "She is a good student.", "turkishSentence": "O iyi bir öğrenci." },
    { "english": "Basis", "turkish": "Temel", "englishSentence": "On a daily basis.", "turkishSentence": "Günlük bazda." },
    { "english": "Population", "turkish": "Nüfus", "englishSentence": "The population is growing.", "turkishSentence": "Nüfus artıyor." },
    { "english": "Material", "turkish": "Malzeme", "englishSentence": "What material is this?", "turkishSentence": "Bu ne malzeme?" },
    { "english": "Hell", "turkish": "Cehennem", "englishSentence": "What the hell happened?", "turkishSentence": "Ne oldu böyle?" },
    { "english": "Summer", "turkish": "Yaz", "englishSentence": "I love summer.", "turkishSentence": "Yazı seviyorum." },
    { "english": "Floor", "turkish": "Kat / Zemin", "englishSentence": "I live on the second floor.", "turkishSentence": "İkinci katta yaşıyorum." },
    { "english": "Funny", "turkish": "Komik", "englishSentence": "That was really funny.", "turkishSentence": "Bu gerçekten komikti." },
    { "english": "Choice", "turkish": "Seçim", "englishSentence": "You have a choice.", "turkishSentence": "Bir seçeneğin var." },
    { "english": "List", "turkish": "Liste", "englishSentence": "Make a shopping list.", "turkishSentence": "Bir alışveriş listesi yap." },
    { "english": "Model", "turkish": "Model", "englishSentence": "This is the latest model.", "turkishSentence": "Bu en son model." },
    { "english": "Blue", "turkish": "Mavi", "englishSentence": "The sky is blue.", "turkishSentence": "Gökyüzü mavi." },
    // Sub-list 11
    { "english": "Approach", "turkish": "Yaklaşım", "englishSentence": "We need a new approach.", "turkishSentence": "Yeni bir yaklaşıma ihtiyacımız var." },
    { "english": "Pressure", "turkish": "Baskı", "englishSentence": "I'm under pressure.", "turkishSentence": "Baskı altındayım." },
    { "english": "Island", "turkish": "Ada", "englishSentence": "They live on an island.", "turkishSentence": "Bir adada yaşıyorlar." },
    { "english": "Fish", "turkish": "Balık", "englishSentence": "I like eating fish.", "turkishSentence": "Balık yemeyi severim." },
    { "english": "Cover", "turkish": "Kapak / Örtmek", "englishSentence": "Cover the pot.", "turkishSentence": "Tencerenin kapağını kapat." },
    { "english": "Computer", "turkish": "Bilgisayar", "englishSentence": "I use a computer every day.", "turkishSentence": "Her gün bilgisayar kullanıyorum." },
    { "english": "Picture", "turkish": "Resim / Fotoğraf", "englishSentence": "Can you take a picture?", "turkishSentence": "Fotoğraf çekebilir misin?" },
    { "english": "Sign", "turkish": "İşaret / İmzalamak", "englishSentence": "Please sign here.", "turkishSentence": "Lütfen buraya imzalayın." },
    { "english": "Clearly", "turkish": "Açıkça", "englishSentence": "Speak clearly, please.", "turkishSentence": "Lütfen açıkça konuş." },
    { "english": "Afternoon", "turkish": "Öğleden sonra", "englishSentence": "Good afternoon!", "turkishSentence": "İyi günler!" },
    { "english": "Science", "turkish": "Bilim", "englishSentence": "I love science.", "turkishSentence": "Bilimi seviyorum." },
    { "english": "Movement", "turkish": "Hareket", "englishSentence": "The movement was fast.", "turkishSentence": "Hareket hızlıydı." },
    { "english": "Expect", "turkish": "Beklemek / Ummak", "englishSentence": "I expect good results.", "turkishSentence": "İyi sonuçlar bekliyorum." },
    { "english": "Capital", "turkish": "Başkent / Sermaye", "englishSentence": "Ankara is the capital.", "turkishSentence": "Ankara başkenttir." },
    { "english": "Economy", "turkish": "Ekonomi", "englishSentence": "The economy is improving.", "turkishSentence": "Ekonomi iyileşiyor." },
    { "english": "Culture", "turkish": "Kültür", "englishSentence": "I love Turkish culture.", "turkishSentence": "Türk kültürünü seviyorum." },
    { "english": "Teaching", "turkish": "Öğretmenlik", "englishSentence": "Teaching is a noble job.", "turkishSentence": "Öğretmenlik asil bir meslektir." },
    { "english": "Sea", "turkish": "Deniz", "englishSentence": "The sea is calm today.", "turkishSentence": "Deniz bugün sakin." },
    { "english": "Drink", "turkish": "İçmek / İçecek", "englishSentence": "Would you like a drink?", "turkishSentence": "Bir içecek ister misin?" },
    { "english": "Christmas", "turkish": "Noel", "englishSentence": "Merry Christmas!", "turkishSentence": "Mutlu Noeller!" },
    { "english": "Pick", "turkish": "Seçmek / Toplamak", "englishSentence": "Pick a card.", "turkishSentence": "Bir kart seç." },
    { "english": "Hotel", "turkish": "Otel", "englishSentence": "We stayed at a nice hotel.", "turkishSentence": "Güzel bir otelde kaldık." },
    { "english": "Complete", "turkish": "Tamamlamak / Tam", "englishSentence": "The project is complete.", "turkishSentence": "Proje tamamlandı." },
    { "english": "Authority", "turkish": "Otorite / Yetki", "englishSentence": "He has no authority here.", "turkishSentence": "Burada yetkisi yok." },
    { "english": "Fast", "turkish": "Hızlı", "englishSentence": "The car is very fast.", "turkishSentence": "Araba çok hızlı." },
    { "english": "River", "turkish": "Nehir", "englishSentence": "The river is very long.", "turkishSentence": "Nehir çok uzun." },
    { "english": "Truth", "turkish": "Gerçek", "englishSentence": "Tell me the truth.", "turkishSentence": "Bana gerçeği söyle." },
    { "english": "Bye", "turkish": "Hoşça kal", "englishSentence": "Bye, see you later!", "turkishSentence": "Hoşça kal, sonra görüşürüz!" },
    { "english": "Film", "turkish": "Film", "englishSentence": "Let's watch a film.", "turkishSentence": "Bir film izleyelim." },
    { "english": "Continue", "turkish": "Devam etmek", "englishSentence": "Please continue.", "turkishSentence": "Lütfen devam et." }
];
