// BBC 800 Essential Words - Part 5 (Sub-list 9-11)
const wordsPart5 = [
    // Sub-list 9
    { "english": "Finally", "turkish": "Sonunda", "englishSentence": "We finally arrived.", "turkishSentence": "Sonunda vardık." },
    { "english": "Quality", "turkish": "Kalite", "englishSentence": "This is high quality.", "turkishSentence": "Bu yüksek kalite." },
    { "english": "Happen", "turkish": "Olmak / Gerçekleşmek", "englishSentence": "What happened yesterday?", "turkishSentence": "Dün ne oldu?" },
    { "english": "Amount", "turkish": "Miktar", "englishSentence": "What is the total amount?", "turkishSentence": "Toplam miktar ne?" },
    { "english": "Role", "turkish": "Rol", "englishSentence": "He plays an important role.", "turkishSentence": "O önemli bir rol oynuyor." },
    { "english": "Force", "turkish": "Güç / Zorlamak", "englishSentence": "Don't force the door.", "turkishSentence": "Kapıyı zorlama." },
    { "english": "Difference", "turkish": "Fark", "englishSentence": "What's the difference?", "turkishSentence": "Fark ne?" },
    { "english": "Phone", "turkish": "Telefon", "englishSentence": "My phone is ringing.", "turkishSentence": "Telefonum çalıyor." },
    { "english": "Forward", "turkish": "İleri", "englishSentence": "Please move forward.", "turkishSentence": "Lütfen ileri git." },
    { "english": "Member", "turkish": "Üye", "englishSentence": "She is a member of our team.", "turkishSentence": "O takımımızın bir üyesi." },
    { "english": "Letter", "turkish": "Mektup / Harf", "englishSentence": "I received a letter today.", "turkishSentence": "Bugün bir mektup aldım." },
    { "english": "Range", "turkish": "Aralık / Menzil", "englishSentence": "Prices are in this range.", "turkishSentence": "Fiyatlar bu aralıkta." },
    { "english": "Bank", "turkish": "Banka", "englishSentence": "I need to go to the bank.", "turkishSentence": "Bankaya gitmem gerekiyor." },
    { "english": "Central", "turkish": "Merkezi", "englishSentence": "This is the central station.", "turkishSentence": "Burası merkez istasyon." },
    { "english": "Hello", "turkish": "Merhaba", "englishSentence": "Hello, how can I help?", "turkishSentence": "Merhaba, nasıl yardımcı olabilirim?" },
    { "english": "Throat", "turkish": "Boğaz", "englishSentence": "I have a sore throat.", "turkishSentence": "Boğazım ağrıyor." },
    { "english": "Hospital", "turkish": "Hastane", "englishSentence": "She works at the hospital.", "turkishSentence": "Hastanede çalışıyor." },
    { "english": "Simply", "turkish": "Basitçe / Sadece", "englishSentence": "Simply follow the instructions.", "turkishSentence": "Basitçe talimatları takip et." },
    { "english": "Walk", "turkish": "Yürümek", "englishSentence": "Let's walk to the park.", "turkishSentence": "Parka yürüyelim." },
    { "english": "Hit", "turkish": "Vurmak / İsabet", "englishSentence": "He hit the ball.", "turkishSentence": "Topa vurdu." },
    { "english": "Ground", "turkish": "Zemin / Yer", "englishSentence": "The ball hit the ground.", "turkishSentence": "Top yere düştü." },
    { "english": "Obviously", "turkish": "Açıkça / Belli ki", "englishSentence": "Obviously, we need help.", "turkishSentence": "Açıkça, yardıma ihtiyacımız var." },
    { "english": "East", "turkish": "Doğu", "englishSentence": "The sun rises in the east.", "turkishSentence": "Güneş doğudan doğar." },
    { "english": "Eat", "turkish": "Yemek yemek", "englishSentence": "Let's eat dinner.", "turkishSentence": "Akşam yemeği yiyelim." },
    { "english": "Learn", "turkish": "Öğrenmek", "englishSentence": "I want to learn Turkish.", "turkishSentence": "Türkçe öğrenmek istiyorum." },
    { "english": "Price", "turkish": "Fiyat", "englishSentence": "What is the price?", "turkishSentence": "Fiyatı ne?" },
    { "english": "Foreign", "turkish": "Yabancı", "englishSentence": "He speaks a foreign language.", "turkishSentence": "Yabancı bir dil konuşuyor." },
    { "english": "Recent", "turkish": "Son / Yakın zamandaki", "englishSentence": "Recent events are worrying.", "turkishSentence": "Son olaylar endişe verici." },
    { "english": "Final", "turkish": "Son / Final", "englishSentence": "This is the final decision.", "turkishSentence": "Bu son karar." },
    { "english": "Beginning", "turkish": "Başlangıç", "englishSentence": "This is just the beginning.", "turkishSentence": "Bu sadece başlangıç." },
    { "english": "Tomorrow", "turkish": "Yarın", "englishSentence": "See you tomorrow.", "turkishSentence": "Yarın görüşürüz." },
    { "english": "Writing", "turkish": "Yazı / Yazma", "englishSentence": "I enjoy creative writing.", "turkishSentence": "Yaratıcı yazmayı seviyorum." },
    { "english": "Return", "turkish": "Dönmek / İade", "englishSentence": "I will return soon.", "turkishSentence": "Yakında döneceğim." },
    { "english": "Break", "turkish": "Kırmak / Mola", "englishSentence": "Let's take a break.", "turkishSentence": "Biraz mola verelim." },
    { "english": "Lead", "turkish": "Öncülük etmek / Kurşun", "englishSentence": "She will lead the team.", "turkishSentence": "Takıma liderlik edecek." },
    { "english": "Project", "turkish": "Proje", "englishSentence": "The project is almost done.", "turkishSentence": "Proje neredeyse bitti." },
    { "english": "Due", "turkish": "Nedeniyle / Vadesi gelen", "englishSentence": "The book is due tomorrow.", "turkishSentence": "Kitabın iadesi yarın." },
    { "english": "Knowledge", "turkish": "Bilgi", "englishSentence": "Knowledge is power.", "turkishSentence": "Bilgi güçtür." },
    { "english": "Decision", "turkish": "Karar", "englishSentence": "I made a decision.", "turkishSentence": "Bir karar verdim." },
    { "english": "Minute", "turkish": "Dakika", "englishSentence": "Wait a minute.", "turkishSentence": "Bir dakika bekle." },
    { "english": "Analysis", "turkish": "Analiz", "englishSentence": "We need more analysis.", "turkishSentence": "Daha fazla analize ihtiyacımız var." },
    { "english": "Beautiful", "turkish": "Güzel", "englishSentence": "The view is beautiful.", "turkishSentence": "Manzara güzel." },
    { "english": "Check", "turkish": "Kontrol etmek", "englishSentence": "Please check the email.", "turkishSentence": "Lütfen e-postayı kontrol et." },
    { "english": "Post", "turkish": "Posta / Gönderi", "englishSentence": "I'll post it today.", "turkishSentence": "Bugün göndereceğim." },
    { "english": "Attention", "turkish": "Dikkat", "englishSentence": "Pay attention!", "turkishSentence": "Dikkat et!" },
    { "english": "Hair", "turkish": "Saç", "englishSentence": "She has long hair.", "turkishSentence": "Uzun saçları var." },
    { "english": "Cold", "turkish": "Soğuk / Soğuk algınlığı", "englishSentence": "It's cold outside.", "turkishSentence": "Dışarısı soğuk." },
    { "english": "Evening", "turkish": "Akşam", "englishSentence": "Good evening!", "turkishSentence": "İyi akşamlar!" },
    { "english": "Reading", "turkish": "Okuma", "englishSentence": "I enjoy reading books.", "turkishSentence": "Kitap okumayı seviyorum." },
    // Sub-list 10
    { "english": "President", "turkish": "Başkan", "englishSentence": "The president gave a speech.", "turkishSentence": "Başkan bir konuşma yaptı." },
    { "english": "Standard", "turkish": "Standart", "englishSentence": "This is the standard procedure.", "turkishSentence": "Bu standart prosedür." },
    { "english": "Wish", "turkish": "Dilek / İstemek", "englishSentence": "I wish you success.", "turkishSentence": "Sana başarılar dilerim." },
    { "english": "Fun", "turkish": "Eğlence", "englishSentence": "We had a lot of fun.", "turkishSentence": "Çok eğlendik." },
    { "english": "Security", "turkish": "Güvenlik", "englishSentence": "Security is very important.", "turkishSentence": "Güvenlik çok önemli." },
    { "english": "Production", "turkish": "Üretim", "englishSentence": "Production has increased.", "turkishSentence": "Üretim arttı." },
    { "english": "Record", "turkish": "Kayıt / Rekor", "englishSentence": "He broke the record.", "turkishSentence": "Rekoru kırdı." },
    { "english": "Serious", "turkish": "Ciddi", "englishSentence": "This is a serious matter.", "turkishSentence": "Bu ciddi bir mesele." },
    { "english": "Financial", "turkish": "Finansal", "englishSentence": "They have financial problems.", "turkishSentence": "Finansal sorunları var." },
    { "english": "Send", "turkish": "Göndermek", "englishSentence": "Please send me an email.", "turkishSentence": "Lütfen bana e-posta gönder." },
    { "english": "Dog", "turkish": "Köpek", "englishSentence": "I have a dog.", "turkishSentence": "Bir köpeğim var." },
    { "english": "Degree", "turkish": "Derece / Diploma", "englishSentence": "She has a degree in law.", "turkishSentence": "Hukuk diploması var." },
    { "english": "Dear", "turkish": "Sevgili / Pahalı", "englishSentence": "Dear friends,", "turkishSentence": "Sevgili arkadaşlar," },
    { "english": "Date", "turkish": "Tarih / Randevu", "englishSentence": "What is today's date?", "turkishSentence": "Bugünün tarihi ne?" },
    { "english": "Normal", "turkish": "Normal", "englishSentence": "Everything is normal.", "turkishSentence": "Her şey normal." }
];
