// BBC 800 Essential Words - Part 3 (Sub-list 5-6)
const wordsPart3 = [
    // Sub-list 5
    { "english": "Fine", "turkish": "İyi / Hoş / Ceza", "englishSentence": "I'm fine, thank you.", "turkishSentence": "İyiyim, teşekkürler." },
    { "english": "Food", "turkish": "Yiyecek / Gıda", "englishSentence": "The food here is delicious.", "turkishSentence": "Buradaki yemek lezzetli." },
    { "english": "Wrong", "turkish": "Yanlış", "englishSentence": "Something is wrong here.", "turkishSentence": "Burada yanlış bir şey var." },
    { "english": "Reason", "turkish": "Sebep / Neden", "englishSentence": "What is the reason for this?", "turkishSentence": "Bunun sebebi ne?" },
    { "english": "Boy", "turkish": "Erkek çocuk", "englishSentence": "The boy is playing in the garden.", "turkishSentence": "Çocuk bahçede oynuyor." },
    { "english": "Certain", "turkish": "Kesin / Belirli", "englishSentence": "I am certain about this.", "turkishSentence": "Bu konuda eminim." },
    { "english": "Moment", "turkish": "An / Dakika", "englishSentence": "Wait a moment, please.", "turkishSentence": "Bir dakika bekle lütfen." },
    { "english": "Further", "turkish": "Daha ileri / Ayrıca", "englishSentence": "We need to discuss this further.", "turkishSentence": "Bunu daha fazla tartışmamız gerekiyor." },
    { "english": "Black", "turkish": "Siyah", "englishSentence": "She wears a black dress.", "turkishSentence": "Siyah bir elbise giyiyor." },
    { "english": "Research", "turkish": "Araştırma", "englishSentence": "We need more research on this.", "turkishSentence": "Bu konuda daha fazla araştırmaya ihtiyacımız var." },
    { "english": "Turn", "turkish": "Dönmek / Sıra", "englishSentence": "It's your turn now.", "turkishSentence": "Şimdi senin sıran." },
    { "english": "Sense", "turkish": "His / Anlam", "englishSentence": "This doesn't make sense.", "turkishSentence": "Bunun bir anlamı yok." },
    { "english": "Move", "turkish": "Hareket etmek / Taşınmak", "englishSentence": "We are going to move next month.", "turkishSentence": "Gelecek ay taşınacağız." },
    { "english": "Human", "turkish": "İnsan", "englishSentence": "Every human has rights.", "turkishSentence": "Her insanın hakları vardır." },
    { "english": "Light", "turkish": "Işık / Hafif", "englishSentence": "Turn on the light, please.", "turkishSentence": "Lütfen ışığı aç." },
    { "english": "Control", "turkish": "Kontrol", "englishSentence": "She has everything under control.", "turkishSentence": "O her şeyi kontrol altında tutuyor." },
    { "english": "Law", "turkish": "Hukuk / Yasa", "englishSentence": "Everyone must obey the law.", "turkishSentence": "Herkes yasalara uymalı." },
    { "english": "Guy", "turkish": "Adam / Herif", "englishSentence": "He's a nice guy.", "turkishSentence": "O iyi bir adam." },
    { "english": "University", "turkish": "Üniversite", "englishSentence": "She goes to university.", "turkishSentence": "Üniversiteye gidiyor." },
    { "english": "Data", "turkish": "Veri", "englishSentence": "We need more data to analyze.", "turkishSentence": "Analiz etmek için daha fazla veriye ihtiyacımız var." },
    { "english": "Sometimes", "turkish": "Bazen", "englishSentence": "Sometimes I feel tired.", "turkishSentence": "Bazen yorgun hissederim." },
    { "english": "Programme", "turkish": "Program", "englishSentence": "The programme starts at eight.", "turkishSentence": "Program sekizde başlıyor." },
    { "english": "Girl", "turkish": "Kız", "englishSentence": "The girl is reading a book.", "turkishSentence": "Kız bir kitap okuyor." },
    { "english": "Body", "turkish": "Vücut / Beden", "englishSentence": "Exercise is good for the body.", "turkishSentence": "Egzersiz vücut için iyidir." },
    { "english": "Wait", "turkish": "Beklemek", "englishSentence": "Please wait a moment.", "turkishSentence": "Lütfen bir dakika bekleyin." },
    { "english": "Political", "turkish": "Siyasi", "englishSentence": "She has strong political views.", "turkishSentence": "Güçlü siyasi görüşleri var." },
    { "english": "Free", "turkish": "Özgür / Ücretsiz", "englishSentence": "The concert is free.", "turkishSentence": "Konser ücretsiz." },
    { "english": "Wife", "turkish": "Eş / Karı", "englishSentence": "His wife is a teacher.", "turkishSentence": "Eşi bir öğretmen." },
    { "english": "Act", "turkish": "Davranmak / Hareket", "englishSentence": "We must act quickly.", "turkishSentence": "Hızlı hareket etmeliyiz." },
    { "english": "Road", "turkish": "Yol", "englishSentence": "The road was long and dusty.", "turkishSentence": "Yol uzun ve tozluydu." },
    { "english": "Top", "turkish": "Üst / Zirve", "englishSentence": "He reached the top of the mountain.", "turkishSentence": "Dağın zirvesine ulaştı." },
    { "english": "Front", "turkish": "Ön / Ön taraf", "englishSentence": "Wait for me in front of the building.", "turkishSentence": "Binanın önünde beni bekle." },
    { "english": "Education", "turkish": "Eğitim", "englishSentence": "Education is very important.", "turkishSentence": "Eğitim çok önemlidir." },
    { "english": "Hope", "turkish": "Umut / Ummak", "englishSentence": "I hope you feel better.", "turkishSentence": "Umarım daha iyi hissedersin." },
    { "english": "Particular", "turkish": "Belirli / Özel", "englishSentence": "Is there a particular reason?", "turkishSentence": "Belirli bir sebep var mı?" },
    { "english": "Story", "turkish": "Hikaye / Öykü", "englishSentence": "Tell me a story.", "turkishSentence": "Bana bir hikaye anlat." },
    { "english": "Language", "turkish": "Dil", "englishSentence": "Learning a new language is fun.", "turkishSentence": "Yeni bir dil öğrenmek eğlenceli." },
    { "english": "Close", "turkish": "Kapatmak / Yakın", "englishSentence": "Please close the door.", "turkishSentence": "Lütfen kapıyı kapat." },
    { "english": "Child", "turkish": "Çocuk", "englishSentence": "Every child deserves love.", "turkishSentence": "Her çocuk sevgiyi hak eder." },
    { "english": "Paper", "turkish": "Kağıt / Gazete", "englishSentence": "I need a piece of paper.", "turkishSentence": "Bir parça kağıda ihtiyacım var." },
    { "english": "Door", "turkish": "Kapı", "englishSentence": "Someone is knocking on the door.", "turkishSentence": "Birisi kapıyı çalıyor." },
    { "english": "Study", "turkish": "Çalışmak / Ders çalışmak", "englishSentence": "I need to study for the exam.", "turkishSentence": "Sınav için çalışmam gerekiyor." },
    { "english": "Stop", "turkish": "Durmak / Durdurmak", "englishSentence": "Stop making noise!", "turkishSentence": "Gürültü yapmayı bırak!" },
    { "english": "Interest", "turkish": "İlgi / Faiz", "englishSentence": "I have an interest in music.", "turkishSentence": "Müziğe ilgim var." },
    { "english": "View", "turkish": "Görüş / Manzara", "englishSentence": "The view from here is amazing.", "turkishSentence": "Buradan manzara muhteşem." },
    { "english": "Hear", "turkish": "Duymak", "englishSentence": "I can hear the birds singing.", "turkishSentence": "Kuşların şarkı söylediğini duyabiliyorum." },
    { "english": "White", "turkish": "Beyaz", "englishSentence": "She wore a white dress.", "turkishSentence": "Beyaz bir elbise giydi." },
    { "english": "Class", "turkish": "Sınıf / Ders", "englishSentence": "The class starts at nine.", "turkishSentence": "Ders dokuzda başlıyor." },
    { "english": "Air", "turkish": "Hava", "englishSentence": "The air is fresh here.", "turkishSentence": "Buranın havası temiz." },
    { "english": "Major", "turkish": "Büyük / Ana / Önemli", "englishSentence": "This is a major decision.", "turkishSentence": "Bu önemli bir karar." },

    // Sub-list 6
    { "english": "Thinking", "turkish": "Düşünme / Düşünce", "englishSentence": "I was thinking about you.", "turkishSentence": "Seni düşünüyordum." },
    { "english": "Stay", "turkish": "Kalmak", "englishSentence": "Please stay a little longer.", "turkishSentence": "Lütfen biraz daha kal." },
    { "english": "Late", "turkish": "Geç", "englishSentence": "Sorry, I'm late.", "turkishSentence": "Özür dilerim, geç kaldım." },
    { "english": "Cut", "turkish": "Kesmek", "englishSentence": "Be careful not to cut yourself.", "turkishSentence": "Kendini kesmemeye dikkat et." },
    { "english": "Short", "turkish": "Kısa", "englishSentence": "It was a short meeting.", "turkishSentence": "Kısa bir toplantıydı." },
    { "english": "Mrs.", "turkish": "Bayan", "englishSentence": "Mrs. Johnson is our neighbor.", "turkishSentence": "Bayan Johnson bizim komşumuz." },
    { "english": "Deal", "turkish": "Anlaşma / İlgilenmek", "englishSentence": "We made a deal.", "turkishSentence": "Bir anlaşma yaptık." },
    { "english": "Community", "turkish": "Topluluk", "englishSentence": "We live in a close community.", "turkishSentence": "Yakın bir toplulukta yaşıyoruz." },
    { "english": "Living", "turkish": "Yaşam / Yaşayan", "englishSentence": "What do you do for a living?", "turkishSentence": "Geçimini ne yaparak sağlıyorsun?" },
    { "english": "News", "turkish": "Haber", "englishSentence": "Did you hear the latest news?", "turkishSentence": "Son haberleri duydun mu?" },
    { "english": "Market", "turkish": "Pazar / Piyasa", "englishSentence": "I go to the market every Saturday.", "turkishSentence": "Her cumartesi pazara giderim." },
    { "english": "South", "turkish": "Güney", "englishSentence": "They moved to the south.", "turkishSentence": "Güneye taşındılar." },
    { "english": "Age", "turkish": "Yaş / Çağ", "englishSentence": "What is your age?", "turkishSentence": "Kaç yaşındasın?" },
    { "english": "Report", "turkish": "Rapor / Bildirmek", "englishSentence": "The report is due tomorrow.", "turkishSentence": "Raporun teslim tarihi yarın." },
    { "english": "Cost", "turkish": "Maliyet / Mal olmak", "englishSentence": "How much does it cost?", "turkishSentence": "Ne kadara mal oluyor?" },
    { "english": "Friend", "turkish": "Arkadaş", "englishSentence": "She is a good friend of mine.", "turkishSentence": "O benim iyi bir arkadaşım." },
    { "english": "Difficult", "turkish": "Zor", "englishSentence": "This exam is very difficult.", "turkishSentence": "Bu sınav çok zor." },
    { "english": "Future", "turkish": "Gelecek", "englishSentence": "The future looks bright.", "turkishSentence": "Gelecek parlak görünüyor." },
    { "english": "Town", "turkish": "Kasaba", "englishSentence": "I grew up in a small town.", "turkishSentence": "Küçük bir kasabada büyüdüm." },
    { "english": "Death", "turkish": "Ölüm", "englishSentence": "Death is a part of life.", "turkishSentence": "Ölüm hayatın bir parçası." },
    { "english": "Support", "turkish": "Destek / Desteklemek", "englishSentence": "I need your support.", "turkishSentence": "Desteğine ihtiyacım var." },
    { "english": "Soon", "turkish": "Yakında / Çok geçmeden", "englishSentence": "I will be there soon.", "turkishSentence": "Yakında orada olacağım." },
    { "english": "Economic", "turkish": "Ekonomik", "englishSentence": "The economic situation is improving.", "turkishSentence": "Ekonomik durum iyileşiyor." },
    { "english": "Music", "turkish": "Müzik", "englishSentence": "I love listening to music.", "turkishSentence": "Müzik dinlemeyi seviyorum." },
    { "english": "Figure", "turkish": "Rakam / Figür / Anlamak", "englishSentence": "I can't figure out this problem.", "turkishSentence": "Bu problemi çözemiyorum." },
    { "english": "Clear", "turkish": "Açık / Net / Temiz", "englishSentence": "The instructions are clear.", "turkishSentence": "Talimatlar net." },
    { "english": "Usually", "turkish": "Genellikle", "englishSentence": "I usually wake up at seven.", "turkishSentence": "Genellikle yedide uyanırım." },
    { "english": "Position", "turkish": "Konum / Pozisyon", "englishSentence": "She applied for the position.", "turkishSentence": "Pozisyona başvurdu." },
    { "english": "Health", "turkish": "Sağlık", "englishSentence": "Health is the most important thing.", "turkishSentence": "Sağlık en önemli şeydir." },
    { "english": "Land", "turkish": "Arazi / Toprak / Karaya çıkmak", "englishSentence": "They own a piece of land.", "turkishSentence": "Bir parça araziye sahipler." },
    { "english": "Police", "turkish": "Polis", "englishSentence": "The police arrived quickly.", "turkishSentence": "Polis hızla geldi." },
    { "english": "Bring", "turkish": "Getirmek", "englishSentence": "Please bring me a glass of water.", "turkishSentence": "Lütfen bana bir bardak su getir." },
    { "english": "Period", "turkish": "Dönem / Süre", "englishSentence": "This is a difficult period.", "turkishSentence": "Bu zor bir dönem." },
    { "english": "Buy", "turkish": "Satın almak", "englishSentence": "I want to buy a new phone.", "turkishSentence": "Yeni bir telefon almak istiyorum." },
    { "english": "Process", "turkish": "Süreç / İşlem", "englishSentence": "The process takes a long time.", "turkishSentence": "Süreç uzun zaman alıyor." },
    { "english": "Department", "turkish": "Bölüm / Departman", "englishSentence": "She works in the sales department.", "turkishSentence": "Satış departmanında çalışıyor." },
    { "english": "Society", "turkish": "Toplum", "englishSentence": "We live in a modern society.", "turkishSentence": "Modern bir toplumda yaşıyoruz." },
    { "english": "Policy", "turkish": "Politika / Poliçe", "englishSentence": "The company has a strict policy.", "turkishSentence": "Şirketin katı bir politikası var." },
    { "english": "Certainly", "turkish": "Kesinlikle", "englishSentence": "I will certainly be there.", "turkishSentence": "Kesinlikle orada olacağım." },
    { "english": "Meeting", "turkish": "Toplantı", "englishSentence": "The meeting starts at ten.", "turkishSentence": "Toplantı onda başlıyor." },
    { "english": "Table", "turkish": "Masa", "englishSentence": "Put the plates on the table.", "turkishSentence": "Tabakları masaya koy." },
    { "english": "History", "turkish": "Tarih", "englishSentence": "History teaches us many things.", "turkishSentence": "Tarih bize birçok şey öğretir." },
    { "english": "Special", "turkish": "Özel", "englishSentence": "Today is a special day.", "turkishSentence": "Bugün özel bir gün." },
    { "english": "Type", "turkish": "Tür / Yazmak", "englishSentence": "What type of music do you like?", "turkishSentence": "Ne tür müzik seversin?" },
    { "english": "Seem", "turkish": "Görünmek / Gibi görünmek", "englishSentence": "You seem tired today.", "turkishSentence": "Bugün yorgun görünüyorsun." },
    { "english": "Experience", "turkish": "Deneyim / Tecrübe", "englishSentence": "She has a lot of experience.", "turkishSentence": "Çok fazla deneyimi var." },
    { "english": "Couple", "turkish": "Çift / Birkaç", "englishSentence": "We waited a couple of hours.", "turkishSentence": "Birkaç saat bekledik." },
    { "english": "Centre", "turkish": "Merkez", "englishSentence": "The shop is in the city centre.", "turkishSentence": "Dükkan şehir merkezinde." },
    { "english": "Street", "turkish": "Sokak / Cadde", "englishSentence": "I live on a quiet street.", "turkishSentence": "Sessiz bir sokakta yaşıyorum." },
    { "english": "Interesting", "turkish": "İlginç", "englishSentence": "That's an interesting idea.", "turkishSentence": "Bu ilginç bir fikir." }
];
