// BBC 800 Essential Words - Part 1 (Sub-list 1-2)
const wordsPart1 = [
    // Sub-list 1
    { "english": "Know", "turkish": "Bilmek / Tanımak", "englishSentence": "I know the answer.", "turkishSentence": "Cevabı biliyorum." },
    { "english": "Go", "turkish": "Gitmek", "englishSentence": "We should go to the park.", "turkishSentence": "Parka gitmeliyiz." },
    { "english": "Like", "turkish": "Sevmek / Gibi", "englishSentence": "I like drinking coffee.", "turkishSentence": "Kahve içmeyi severim." },
    { "english": "Yes", "turkish": "Evet", "englishSentence": "Yes, I agree with you.", "turkishSentence": "Evet, sana katılıyorum." },
    { "english": "Well", "turkish": "İyi / Peki", "englishSentence": "She speaks English very well.", "turkishSentence": "O çok iyi İngilizce konuşuyor." },
    { "english": "Very", "turkish": "Çok", "englishSentence": "The exam was very difficult.", "turkishSentence": "Sınav çok zordu." },
    { "english": "Just", "turkish": "Sadece / Az önce", "englishSentence": "I just arrived home.", "turkishSentence": "Az önce eve vardım." },
    { "english": "See", "turkish": "Görmek", "englishSentence": "I can see the mountains from here.", "turkishSentence": "Buradan dağları görebiliyorum." },
    { "english": "Think", "turkish": "Düşünmek", "englishSentence": "I think it's going to rain.", "turkishSentence": "Bence yağmur yağacak." },
    { "english": "People", "turkish": "İnsanlar", "englishSentence": "There were many people at the party.", "turkishSentence": "Partide birçok insan vardı." },
    { "english": "Right", "turkish": "Doğru / Sağ / Hak", "englishSentence": "You are right about this.", "turkishSentence": "Bu konuda haklısın." },
    { "english": "Here", "turkish": "Burada / Buraya", "englishSentence": "Please wait for me here.", "turkishSentence": "Lütfen burada beni bekle." },
    { "english": "Then", "turkish": "O zaman / Sonra", "englishSentence": "I had breakfast, then went to work.", "turkishSentence": "Kahvaltı ettim, sonra işe gittim." },
    { "english": "Good", "turkish": "İyi / Güzel", "englishSentence": "This is a very good movie.", "turkishSentence": "Bu çok iyi bir film." },
    { "english": "Now", "turkish": "Şimdi / Şu an", "englishSentence": "I am busy right now.", "turkishSentence": "Şu an meşgulüm." },
    { "english": "Only", "turkish": "Sadece / Tek", "englishSentence": "I have only one brother.", "turkishSentence": "Sadece bir erkek kardeşim var." },
    { "english": "Get", "turkish": "Almak / Elde etmek", "englishSentence": "Can you get some milk?", "turkishSentence": "Biraz süt alabilir misin?" },
    { "english": "Really", "turkish": "Gerçekten", "englishSentence": "I really enjoyed the concert.", "turkishSentence": "Konserden gerçekten keyif aldım." },
    { "english": "Time", "turkish": "Zaman / Vakit", "englishSentence": "Time flies when having fun.", "turkishSentence": "Eğlenirken zaman uçup gidiyor." },
    { "english": "Say", "turkish": "Söylemek / Demek", "englishSentence": "What did you say?", "turkishSentence": "Ne söyledin?" },
    { "english": "Take", "turkish": "Almak / Götürmek", "englishSentence": "Take your umbrella with you.", "turkishSentence": "Şemsiyeni yanına al." },
    { "english": "Make", "turkish": "Yapmak / Etmek", "englishSentence": "She can make delicious cakes.", "turkishSentence": "O lezzetli kekler yapabilir." },
    { "english": "Long", "turkish": "Uzun", "englishSentence": "It was a long journey.", "turkishSentence": "Uzun bir yolculuktu." },
    { "english": "Need", "turkish": "İhtiyaç / Gerekmek", "englishSentence": "I need your help.", "turkishSentence": "Yardımına ihtiyacım var." },
    { "english": "Year", "turkish": "Yıl", "englishSentence": "This year has been great.", "turkishSentence": "Bu yıl harika geçti." },
    { "english": "Mr.", "turkish": "Bay", "englishSentence": "Mr. Smith is our teacher.", "turkishSentence": "Bay Smith bizim öğretmenimiz." },
    { "english": "Look", "turkish": "Bakmak / Görünmek", "englishSentence": "Look at the beautiful sunset.", "turkishSentence": "Güzel gün batımına bak." },
    { "english": "Thought", "turkish": "Düşünce / Düşündü", "englishSentence": "I thought you were coming.", "turkishSentence": "Geleceğini düşünmüştüm." },
    { "english": "Thing", "turkish": "Şey / Nesne", "englishSentence": "The most important thing is health.", "turkishSentence": "En önemli şey sağlıktır." },
    { "english": "Lot", "turkish": "Çok / Bir sürü", "englishSentence": "I have a lot of work to do.", "turkishSentence": "Yapacak çok işim var." },
    { "english": "Man", "turkish": "Adam / Erkek", "englishSentence": "The man is reading a newspaper.", "turkishSentence": "Adam gazete okuyor." },
    { "english": "Same", "turkish": "Aynı", "englishSentence": "We go to the same school.", "turkishSentence": "Aynı okula gidiyoruz." },
    { "english": "Put", "turkish": "Koymak / Yerleştirmek", "englishSentence": "Put the book on the shelf.", "turkishSentence": "Kitabı rafa koy." },
    { "english": "Old", "turkish": "Eski / Yaşlı", "englishSentence": "My grandfather is very old.", "turkishSentence": "Büyükbabam çok yaşlı." },
    { "english": "Let", "turkish": "İzin vermek / Bırakmak", "englishSentence": "Let me help you.", "turkishSentence": "Sana yardım etmeme izin ver." },
    { "english": "Word", "turkish": "Kelime / Söz", "englishSentence": "I learned a new word today.", "turkishSentence": "Bugün yeni bir kelime öğrendim." },
    { "english": "Day", "turkish": "Gün", "englishSentence": "It was a beautiful day.", "turkishSentence": "Güzel bir gündü." },
    { "english": "Course", "turkish": "Elbette / Kurs", "englishSentence": "Of course, I will help you.", "turkishSentence": "Elbette sana yardım edeceğim." },
    { "english": "Never", "turkish": "Asla / Hiçbir zaman", "englishSentence": "I have never been to Japan.", "turkishSentence": "Hiçbir zaman Japonya'ya gitmedim." },
    { "english": "Life", "turkish": "Hayat / Yaşam", "englishSentence": "Life is full of surprises.", "turkishSentence": "Hayat sürprizlerle dolu." },

    // Sub-list 2
    { "english": "Again", "turkish": "Tekrar / Yeniden", "englishSentence": "Please say that again.", "turkishSentence": "Lütfen bunu tekrar söyle." },
    { "english": "Kind", "turkish": "Tür / Nazik", "englishSentence": "What kind of music do you like?", "turkishSentence": "Ne tür müzik seversin?" },
    { "english": "Point", "turkish": "Nokta / Puan / Anlam", "englishSentence": "What is the point of this?", "turkishSentence": "Bunun anlamı ne?" },
    { "english": "Own", "turkish": "Kendi / Sahip olmak", "englishSentence": "I have my own car.", "turkishSentence": "Kendi arabam var." },
    { "english": "Actually", "turkish": "Aslında", "englishSentence": "Actually, I changed my mind.", "turkishSentence": "Aslında fikrimi değiştirdim." },
    { "english": "Number", "turkish": "Sayı / Numara", "englishSentence": "What is your phone number?", "turkishSentence": "Telefon numaran ne?" },
    { "english": "Night", "turkish": "Gece", "englishSentence": "We stayed up all night.", "turkishSentence": "Bütün gece ayakta kaldık." },
    { "english": "Left", "turkish": "Sol / Ayrıldı / Kalan", "englishSentence": "Turn left at the corner.", "turkishSentence": "Köşeden sola dön." },
    { "english": "Side", "turkish": "Taraf / Yan", "englishSentence": "He sat on the other side.", "turkishSentence": "Diğer tarafta oturdu." },
    { "english": "God", "turkish": "Tanrı / Allah", "englishSentence": "Thank God you are safe.", "turkishSentence": "Çok şükür güvendesin." },
    { "english": "Quite", "turkish": "Oldukça / Epey", "englishSentence": "The movie was quite interesting.", "turkishSentence": "Film oldukça ilginçti." },
    { "english": "Sort", "turkish": "Tür / Çeşit", "englishSentence": "What sort of food is this?", "turkishSentence": "Bu ne tür bir yemek?" },
    { "english": "School", "turkish": "Okul", "englishSentence": "I go to school every day.", "turkishSentence": "Her gün okula gidiyorum." },
    { "english": "Found", "turkish": "Buldu / Kurmak", "englishSentence": "I found the keys under the sofa.", "turkishSentence": "Anahtarları kanepenin altında buldum." },
    { "english": "Week", "turkish": "Hafta", "englishSentence": "I will see you next week.", "turkishSentence": "Seni gelecek hafta göreceğim." },
    { "english": "Give", "turkish": "Vermek", "englishSentence": "Can you give me some water?", "turkishSentence": "Bana biraz su verebilir misin?" },
    { "english": "Home", "turkish": "Ev / Yuva", "englishSentence": "I want to go home.", "turkishSentence": "Eve gitmek istiyorum." },
    { "english": "House", "turkish": "Ev", "englishSentence": "They bought a new house.", "turkishSentence": "Yeni bir ev satın aldılar." },
    { "english": "Tell", "turkish": "Söylemek / Anlatmak", "englishSentence": "Tell me the truth.", "turkishSentence": "Bana doğruyu söyle." },
    { "english": "Find", "turkish": "Bulmak", "englishSentence": "I can't find my keys.", "turkishSentence": "Anahtarlarımı bulamıyorum." },
    { "english": "World", "turkish": "Dünya", "englishSentence": "The world is a beautiful place.", "turkishSentence": "Dünya güzel bir yer." },
    { "english": "Place", "turkish": "Yer / Mekan", "englishSentence": "This is a nice place to live.", "turkishSentence": "Burası yaşamak için güzel bir yer." },
    { "english": "Use", "turkish": "Kullanmak", "englishSentence": "Can I use your phone?", "turkishSentence": "Telefonunu kullanabilir miyim?" },
    { "english": "Different", "turkish": "Farklı", "englishSentence": "We have different opinions.", "turkishSentence": "Farklı görüşlerimiz var." },
    { "english": "Always", "turkish": "Her zaman / Daima", "englishSentence": "She always wakes up early.", "turkishSentence": "O her zaman erken kalkar." },
    { "english": "Part", "turkish": "Parça / Kısım", "englishSentence": "This is the best part of the movie.", "turkishSentence": "Filmin en iyi kısmı bu." },
    { "english": "Great", "turkish": "Harika / Büyük", "englishSentence": "That's a great idea!", "turkishSentence": "Bu harika bir fikir!" },
    { "english": "Sure", "turkish": "Emin / Tabii ki", "englishSentence": "Are you sure about this?", "turkishSentence": "Bundan emin misin?" },
    { "english": "Government", "turkish": "Hükümet", "englishSentence": "The government announced new rules.", "turkishSentence": "Hükümet yeni kurallar açıkladı." },
    { "english": "End", "turkish": "Son / Bitmek", "englishSentence": "This is the end of the movie.", "turkishSentence": "Filmin sonu bu." },
    { "english": "High", "turkish": "Yüksek", "englishSentence": "The mountain is very high.", "turkishSentence": "Dağ çok yüksek." },
    { "english": "Family", "turkish": "Aile", "englishSentence": "Family is the most important thing.", "turkishSentence": "Aile en önemli şeydir." },
    { "english": "Money", "turkish": "Para", "englishSentence": "Money isn't everything.", "turkishSentence": "Para her şey değil." },
    { "english": "Help", "turkish": "Yardım / Yardım etmek", "englishSentence": "Can you help me with this?", "turkishSentence": "Bu konuda bana yardım edebilir misin?" },
    { "english": "Ever", "turkish": "Hiç / Her zaman", "englishSentence": "Have you ever been to London?", "turkishSentence": "Hiç Londra'ya gittin mi?" },
    { "english": "Better", "turkish": "Daha iyi", "englishSentence": "This book is better than that one.", "turkishSentence": "Bu kitap diğerinden daha iyi." },
    { "english": "Maybe", "turkish": "Belki", "englishSentence": "Maybe we should try again.", "turkishSentence": "Belki tekrar denemeliyiz." },
    { "english": "Talk", "turkish": "Konuşmak", "englishSentence": "Can we talk about this later?", "turkishSentence": "Bunu daha sonra konuşabilir miyiz?" },
    { "english": "Big", "turkish": "Büyük", "englishSentence": "He lives in a big city.", "turkishSentence": "Büyük bir şehirde yaşıyor." },
    { "english": "Far", "turkish": "Uzak", "englishSentence": "How far is the airport?", "turkishSentence": "Havalimanı ne kadar uzak?" },
    { "english": "State", "turkish": "Devlet / Durum", "englishSentence": "The state of the economy is improving.", "turkishSentence": "Ekonominin durumu iyileşiyor." },
    { "english": "Probably", "turkish": "Muhtemelen", "englishSentence": "He will probably be late.", "turkishSentence": "Muhtemelen geç kalacak." },
    { "english": "Case", "turkish": "Durum / Dava / Kutu", "englishSentence": "In case of emergency, call this number.", "turkishSentence": "Acil durumda bu numarayı arayın." },
    { "english": "Set", "turkish": "Ayarlamak / Takım", "englishSentence": "Set the alarm for seven.", "turkishSentence": "Alarmı yediye ayarla." },
    { "english": "Fact", "turkish": "Gerçek / Olgu", "englishSentence": "That is a well-known fact.", "turkishSentence": "Bu bilinen bir gerçektir." },
    { "english": "Whole", "turkish": "Bütün / Tam", "englishSentence": "I read the whole book.", "turkishSentence": "Kitabın tamamını okudum." },
    { "english": "Bit", "turkish": "Parça / Biraz", "englishSentence": "Wait a bit, I'm coming.", "turkishSentence": "Biraz bekle, geliyorum." },
    { "english": "Today", "turkish": "Bugün", "englishSentence": "Today is a wonderful day.", "turkishSentence": "Bugün harika bir gün." },
    { "english": "System", "turkish": "Sistem", "englishSentence": "The education system needs reform.", "turkishSentence": "Eğitim sistemi reforma ihtiyaç duyuyor." },
    { "english": "Keep", "turkish": "Tutmak / Saklamak", "englishSentence": "Keep your promises.", "turkishSentence": "Sözlerini tut." }
];
