// BBC 800 Essential Words - Part 2 (Sub-list 4-6)
const wordsPart2 = [
    // Sub-list 4
    { "english": "Company", "turkish": "Şirket / Firma", "englishSentence": "She works for a big company.", "turkishSentence": "Büyük bir şirkette çalışıyor." },
    { "english": "Perhaps", "turkish": "Belki", "englishSentence": "Perhaps we can meet tomorrow.", "turkishSentence": "Belki yarın buluşabiliriz." },
    { "english": "Ago", "turkish": "Önce", "englishSentence": "I met her two years ago.", "turkishSentence": "Onunla iki yıl önce tanıştım." },
    { "english": "Hard", "turkish": "Zor / Sert", "englishSentence": "This is a hard question.", "turkishSentence": "Bu zor bir soru." },
    { "english": "Form", "turkish": "Form / Biçim", "englishSentence": "Please fill out this form.", "turkishSentence": "Lütfen bu formu doldurun." },
    { "english": "Party", "turkish": "Parti / Kutlama", "englishSentence": "We had a great party last night.", "turkishSentence": "Dün gece harika bir parti yaptık." },
    { "english": "Means", "turkish": "Araç / Yol", "englishSentence": "Money is a means to an end.", "turkishSentence": "Para bir amaca ulaşmak için araçtır." },
    { "english": "Often", "turkish": "Sık sık", "englishSentence": "I often go running in the morning.", "turkishSentence": "Sabahları sık sık koşuya giderim." },
    { "english": "Example", "turkish": "Örnek", "englishSentence": "Can you give me an example?", "turkishSentence": "Bana bir örnek verebilir misin?" },
    { "english": "Play", "turkish": "Oynamak / Çalmak", "englishSentence": "Children love to play outside.", "turkishSentence": "Çocuklar dışarıda oynamayı sever." },
    { "english": "Care", "turkish": "İlgilenmek / Önemsemek", "englishSentence": "I care about the environment.", "turkishSentence": "Çevreyi önemsiyorum." },
    { "english": "Ask", "turkish": "Sormak", "englishSentence": "Don't be afraid to ask questions.", "turkishSentence": "Soru sormaktan korkma." },
    { "english": "Pretty", "turkish": "Güzel / Oldukça", "englishSentence": "She is a pretty girl.", "turkishSentence": "O güzel bir kız." },
    { "english": "Possible", "turkish": "Mümkün / Olası", "englishSentence": "Is it possible to finish today?", "turkishSentence": "Bugün bitirmek mümkün mü?" },
    { "english": "Local", "turkish": "Yerel", "englishSentence": "We buy from local farmers.", "turkishSentence": "Yerel çiftçilerden satın alıyoruz." },
    { "english": "Social", "turkish": "Sosyal", "englishSentence": "Social media is very popular.", "turkishSentence": "Sosyal medya çok popüler." },
    { "english": "Matter", "turkish": "Mesele / Önemli olmak", "englishSentence": "It doesn't really matter.", "turkishSentence": "Gerçekten önemli değil." },
    { "english": "Cause", "turkish": "Sebep / Neden olmak", "englishSentence": "What caused the accident?", "turkishSentence": "Kazaya ne sebep oldu?" },
    { "english": "Run", "turkish": "Koşmak", "englishSentence": "I run every morning.", "turkishSentence": "Her sabah koşuyorum." },
    { "english": "Anyway", "turkish": "Her neyse / Zaten", "englishSentence": "Anyway, let's continue.", "turkishSentence": "Her neyse, devam edelim." },
    { "english": "National", "turkish": "Ulusal", "englishSentence": "Today is a national holiday.", "turkishSentence": "Bugün ulusal bir tatil." },
    { "english": "Information", "turkish": "Bilgi", "englishSentence": "I need more information.", "turkishSentence": "Daha fazla bilgiye ihtiyacım var." },
    { "english": "Present", "turkish": "Mevcut / Hediye / Sunmak", "englishSentence": "I have a present for you.", "turkishSentence": "Senin için bir hediyem var." },
    { "english": "Full", "turkish": "Dolu / Tam", "englishSentence": "The bus is full.", "turkishSentence": "Otobüs dolu." },
    { "english": "Office", "turkish": "Ofis", "englishSentence": "I work in an office.", "turkishSentence": "Bir ofiste çalışıyorum." },
    { "english": "Book", "turkish": "Kitap", "englishSentence": "I am reading a book.", "turkishSentence": "Bir kitap okuyorum." },
    { "english": "Hey", "turkish": "Hey / Selam", "englishSentence": "Hey, how are you?", "turkishSentence": "Hey, nasılsın?" },
    { "english": "Leave", "turkish": "Ayrılmak / Bırakmak", "englishSentence": "I have to leave now.", "turkishSentence": "Şimdi gitmem gerekiyor." },
    { "english": "Service", "turkish": "Hizmet / Servis", "englishSentence": "The service here is excellent.", "turkishSentence": "Buradaki hizmet mükemmel." },
    { "english": "Live", "turkish": "Yaşamak / Canlı", "englishSentence": "Where do you live?", "turkishSentence": "Nerede yaşıyorsun?" },
    { "english": "Father", "turkish": "Baba", "englishSentence": "My father is a doctor.", "turkishSentence": "Babam bir doktor." },
    { "english": "Face", "turkish": "Yüz", "englishSentence": "She has a beautiful face.", "turkishSentence": "Güzel bir yüzü var." },
    { "english": "Bad", "turkish": "Kötü", "englishSentence": "That's not a bad idea.", "turkishSentence": "O kötü bir fikir değil." },
    { "english": "Early", "turkish": "Erken", "englishSentence": "I wake up early every morning.", "turkishSentence": "Her sabah erken kalkıyorum." },
    { "english": "Stuff", "turkish": "Malzeme / Şeyler", "englishSentence": "I have a lot of stuff to do.", "turkishSentence": "Yapacak çok işim var." },
    { "english": "Idea", "turkish": "Fikir", "englishSentence": "That's a great idea!", "turkishSentence": "Bu harika bir fikir!" },
    { "english": "Development", "turkish": "Gelişim / Kalkınma", "englishSentence": "The city is under development.", "turkishSentence": "Şehir gelişim altında." },
    { "english": "Level", "turkish": "Seviye / Düzey", "englishSentence": "What is your English level?", "turkishSentence": "İngilizce seviyen ne?" },
    { "english": "War", "turkish": "Savaş", "englishSentence": "Nobody wants war.", "turkishSentence": "Kimse savaş istemez." },
    { "english": "Please", "turkish": "Lütfen", "englishSentence": "Please help me.", "turkishSentence": "Lütfen bana yardım et." },
    { "english": "Large", "turkish": "Büyük / Geniş", "englishSentence": "We live in a large house.", "turkishSentence": "Büyük bir evde yaşıyoruz." },
    { "english": "True", "turkish": "Doğru / Gerçek", "englishSentence": "Is this story true?", "turkishSentence": "Bu hikaye doğru mu?" },
    { "english": "Woman", "turkish": "Kadın", "englishSentence": "She is a strong woman.", "turkishSentence": "O güçlü bir kadın." },
    { "english": "Guess", "turkish": "Tahmin etmek", "englishSentence": "I guess you're right.", "turkishSentence": "Sanırım haklısın." },
    { "english": "Understand", "turkish": "Anlamak", "englishSentence": "I don't understand this.", "turkishSentence": "Bunu anlamıyorum." },
    // Sub-list 5
    { "english": "Fine", "turkish": "İyi / Hoş / Ceza", "englishSentence": "I'm fine, thank you.", "turkishSentence": "İyiyim, teşekkürler." },
    { "english": "Food", "turkish": "Yiyecek / Gıda", "englishSentence": "The food here is delicious.", "turkishSentence": "Buradaki yemek lezzetli." },
    { "english": "Wrong", "turkish": "Yanlış", "englishSentence": "Something is wrong here.", "turkishSentence": "Burada yanlış bir şey var." },
    { "english": "Reason", "turkish": "Sebep / Neden", "englishSentence": "What is the reason for this?", "turkishSentence": "Bunun sebebi ne?" },
    { "english": "Boy", "turkish": "Erkek çocuk", "englishSentence": "The boy is playing in the garden.", "turkishSentence": "Çocuk bahçede oynuyor." },
    { "english": "Research", "turkish": "Araştırma", "englishSentence": "We need more research on this.", "turkishSentence": "Bu konuda daha fazla araştırmaya ihtiyacımız var." },
    { "english": "Certain", "turkish": "Kesin / Belirli", "englishSentence": "I am certain about this.", "turkishSentence": "Bu konuda eminim." },
    { "english": "Moment", "turkish": "An / Dakika", "englishSentence": "Wait a moment, please.", "turkishSentence": "Bir dakika bekle lütfen." },
    { "english": "Further", "turkish": "Daha ileri / Ayrıca", "englishSentence": "We need to discuss this further.", "turkishSentence": "Bunu daha fazla tartışmamız gerekiyor." },
    { "english": "Black", "turkish": "Siyah", "englishSentence": "She wears a black dress.", "turkishSentence": "Siyah bir elbise giyiyor." },
    { "english": "Turn", "turkish": "Dönmek / Sıra", "englishSentence": "It's your turn now.", "turkishSentence": "Şimdi senin sıran." },
    { "english": "Sense", "turkish": "His / Anlam", "englishSentence": "This doesn't make sense.", "turkishSentence": "Bunun bir anlamı yok." },
    { "english": "Move", "turkish": "Hareket etmek / Taşınmak", "englishSentence": "We are going to move next month.", "turkishSentence": "Gelecek ay taşınacağız." },
    { "english": "Human", "turkish": "İnsan", "englishSentence": "Every human has rights.", "turkishSentence": "Her insanın hakları vardır." },
    { "english": "Light", "turkish": "Işık / Hafif", "englishSentence": "Turn on the light, please.", "turkishSentence": "Lütfen ışığı aç." },
    { "english": "Control", "turkish": "Kontrol", "englishSentence": "She has everything under control.", "turkishSentence": "O her şeyi kontrol altında tutuyor." },
    { "english": "Law", "turkish": "Hukuk / Yasa", "englishSentence": "Everyone must obey the law.", "turkishSentence": "Herkes yasalara uymalı." },
    { "english": "Data", "turkish": "Veri", "englishSentence": "We need more data to analyze.", "turkishSentence": "Analiz etmek için daha fazla veriye ihtiyacımız var." }
];
