// BBC 800 Essential Words - Part 4 (Sub-list 7-8)
const wordsPart4 = [
    // Sub-list 7
    { "english": "Rest", "turkish": "Dinlenmek / Geri kalan", "englishSentence": "You need to rest.", "turkishSentence": "Dinlenmen gerekiyor." },
    { "english": "Situation", "turkish": "Durum", "englishSentence": "The situation is getting better.", "turkishSentence": "Durum iyileşiyor." },
    { "english": "Alright", "turkish": "Tamam / İyi", "englishSentence": "Is everything alright?", "turkishSentence": "Her şey yolunda mı?" },
    { "english": "Court", "turkish": "Mahkeme / Saha", "englishSentence": "The case went to court.", "turkishSentence": "Dava mahkemeye gitti." },
    { "english": "Exactly", "turkish": "Tam olarak / Aynen", "englishSentence": "That's exactly what I meant.", "turkishSentence": "Tam olarak kastettiğim buydu." },
    { "english": "Main", "turkish": "Ana / Temel", "englishSentence": "The main entrance is closed.", "turkishSentence": "Ana giriş kapalı." },
    { "english": "Church", "turkish": "Kilise", "englishSentence": "There is an old church in the town.", "turkishSentence": "Kasabada eski bir kilise var." },
    { "english": "Rate", "turkish": "Oran / Hız", "englishSentence": "The crime rate has decreased.", "turkishSentence": "Suç oranı düştü." },
    { "english": "Answer", "turkish": "Cevap / Yanıtlamak", "englishSentence": "I don't know the answer.", "turkishSentence": "Cevabı bilmiyorum." },
    { "english": "Available", "turkish": "Mevcut / Müsait", "englishSentence": "Is this product available?", "turkishSentence": "Bu ürün mevcut mu?" },
    { "english": "Low", "turkish": "Düşük / Alçak", "englishSentence": "The price is very low.", "turkishSentence": "Fiyat çok düşük." },
    { "english": "Effect", "turkish": "Etki / Sonuç", "englishSentence": "What is the effect of this medicine?", "turkishSentence": "Bu ilacın etkisi ne?" },
    { "english": "Private", "turkish": "Özel / Gizli", "englishSentence": "This is a private matter.", "turkishSentence": "Bu özel bir mesele." },
    { "english": "Mum", "turkish": "Anne", "englishSentence": "My mum makes great soup.", "turkishSentence": "Annem harika çorba yapar." },
    { "english": "Meet", "turkish": "Tanışmak / Buluşmak", "englishSentence": "Nice to meet you.", "turkishSentence": "Tanıştığımıza memnun oldum." },
    { "english": "West", "turkish": "Batı", "englishSentence": "The sun sets in the west.", "turkishSentence": "Güneş batıda batar." },
    { "english": "Subject", "turkish": "Konu / Ders", "englishSentence": "What is your favorite subject?", "turkishSentence": "En sevdiğin ders hangisi?" },
    { "english": "College", "turkish": "Kolej / Yüksekokul", "englishSentence": "She studies at a college.", "turkishSentence": "Bir kolejde okuyor." },
    { "english": "Easy", "turkish": "Kolay", "englishSentence": "This exercise is very easy.", "turkishSentence": "Bu alıştırma çok kolay." },
    { "english": "Month", "turkish": "Ay", "englishSentence": "We moved here last month.", "turkishSentence": "Geçen ay buraya taşındık." },
    { "english": "Art", "turkish": "Sanat", "englishSentence": "She has a passion for art.", "turkishSentence": "Sanata karşı tutkusu var." },
    { "english": "Red", "turkish": "Kırmızı", "englishSentence": "She wore a red scarf.", "turkishSentence": "Kırmızı bir eşarp taktı." },
    { "english": "Evidence", "turkish": "Kanıt / Delil", "englishSentence": "There is no evidence of that.", "turkishSentence": "Bunun kanıtı yok." },
    { "english": "Council", "turkish": "Konsey / Meclis", "englishSentence": "The council approved the plan.", "turkishSentence": "Konsey planı onayladı." },
    { "english": "Century", "turkish": "Yüzyıl", "englishSentence": "We live in the 21st century.", "turkishSentence": "21. yüzyılda yaşıyoruz." },
    { "english": "Hour", "turkish": "Saat", "englishSentence": "The movie is two hours long.", "turkishSentence": "Film iki saat sürüyor." },
    { "english": "Dead", "turkish": "Ölü", "englishSentence": "The plant is dead.", "turkishSentence": "Bitki öldü." },
    { "english": "Son", "turkish": "Oğul", "englishSentence": "His son is very talented.", "turkishSentence": "Oğlu çok yetenekli." },
    { "english": "Common", "turkish": "Yaygın / Ortak", "englishSentence": "This is a common mistake.", "turkishSentence": "Bu yaygın bir hata." },
    { "english": "Miss", "turkish": "Özlemek / Kaçırmak", "englishSentence": "I miss my family.", "turkishSentence": "Ailemi özlüyorum." },
    { "english": "North", "turkish": "Kuzey", "englishSentence": "They live in the north of the country.", "turkishSentence": "Ülkenin kuzeyinde yaşıyorlar." },
    { "english": "Particularly", "turkish": "Özellikle", "englishSentence": "I particularly like this song.", "turkishSentence": "Bu şarkıyı özellikle seviyorum." },
    { "english": "Hi", "turkish": "Merhaba", "englishSentence": "Hi, how are you?", "turkishSentence": "Merhaba, nasılsın?" },
    { "english": "Provide", "turkish": "Sağlamak / Temin etmek", "englishSentence": "We will provide all the materials.", "turkishSentence": "Tüm malzemeleri sağlayacağız." },
    { "english": "Watch", "turkish": "İzlemek / Saat", "englishSentence": "I like to watch movies.", "turkishSentence": "Film izlemeyi seviyorum." },
    { "english": "Total", "turkish": "Toplam", "englishSentence": "The total cost is fifty dollars.", "turkishSentence": "Toplam maliyet elli dolar." },
    { "english": "Indeed", "turkish": "Gerçekten / Hakikaten", "englishSentence": "This is indeed a good idea.", "turkishSentence": "Bu gerçekten iyi bir fikir." },
    { "english": "Strong", "turkish": "Güçlü / Kuvvetli", "englishSentence": "He is a strong man.", "turkishSentence": "O güçlü bir adam." },
    { "english": "Staff", "turkish": "Personel / Kadro", "englishSentence": "The staff are very friendly.", "turkishSentence": "Personel çok cana yakın." },
    { "english": "Hold", "turkish": "Tutmak / Düzenlemek", "englishSentence": "Hold my hand.", "turkishSentence": "Elimi tut." },
    { "english": "Happy", "turkish": "Mutlu", "englishSentence": "I am very happy today.", "turkishSentence": "Bugün çok mutluyum." },
    { "english": "Result", "turkish": "Sonuç", "englishSentence": "The result was surprising.", "turkishSentence": "Sonuç şaşırtıcıydı." },
    { "english": "Board", "turkish": "Kurul / Tahta", "englishSentence": "The board approved the budget.", "turkishSentence": "Kurul bütçeyi onayladı." },
    { "english": "Especially", "turkish": "Özellikle", "englishSentence": "I love fruits, especially strawberries.", "turkishSentence": "Meyveleri severim, özellikle çilekleri." },
    { "english": "Building", "turkish": "Bina", "englishSentence": "That building is very tall.", "turkishSentence": "O bina çok yüksek." },
    { "english": "Plan", "turkish": "Plan / Planlamak", "englishSentence": "What's the plan for tomorrow?", "turkishSentence": "Yarın için plan ne?" },
    { "english": "Husband", "turkish": "Koca / Eş", "englishSentence": "Her husband is an engineer.", "turkishSentence": "Kocası bir mühendis." },
    { "english": "Tax", "turkish": "Vergi", "englishSentence": "Taxes are very high this year.", "turkishSentence": "Bu yıl vergiler çok yüksek." },
    { "english": "Stage", "turkish": "Sahne / Aşama", "englishSentence": "We are in the final stage.", "turkishSentence": "Son aşamadayız." },
    { "english": "Committee", "turkish": "Komite / Kurul", "englishSentence": "The committee will decide next week.", "turkishSentence": "Komite gelecek hafta karar verecek." },

    // Sub-list 8
    { "english": "Thanks", "turkish": "Teşekkürler", "englishSentence": "Thanks for your help.", "turkishSentence": "Yardımın için teşekkürler." },
    { "english": "Instead", "turkish": "Bunun yerine", "englishSentence": "Let's walk instead of driving.", "turkishSentence": "Araba kullanmak yerine yürüyelim." },
    { "english": "Ready", "turkish": "Hazır", "englishSentence": "Are you ready to go?", "turkishSentence": "Gitmeye hazır mısın?" },
    { "english": "Individual", "turkish": "Birey / Bireysel", "englishSentence": "Every individual is unique.", "turkishSentence": "Her birey benzersizdir." },
    { "english": "Listen", "turkish": "Dinlemek", "englishSentence": "Listen to the teacher carefully.", "turkishSentence": "Öğretmeni dikkatle dinle." },
    { "english": "Middle", "turkish": "Orta", "englishSentence": "The ball is in the middle of the field.", "turkishSentence": "Top sahanın ortasında." },
    { "english": "Action", "turkish": "Eylem / Hareket", "englishSentence": "We need to take action now.", "turkishSentence": "Şimdi harekete geçmeliyiz." },
    { "english": "Sound", "turkish": "Ses", "englishSentence": "I heard a strange sound.", "turkishSentence": "Garip bir ses duydum." },
    { "english": "Similar", "turkish": "Benzer", "englishSentence": "These two books are very similar.", "turkishSentence": "Bu iki kitap çok benzer." },
    { "english": "Likely", "turkish": "Muhtemel / Olası", "englishSentence": "It is likely to rain tomorrow.", "turkishSentence": "Yarın yağmur yağması muhtemel." },
    { "english": "Suppose", "turkish": "Farz etmek / Sanmak", "englishSentence": "I suppose you are right.", "turkishSentence": "Sanırım haklısın." },
    { "english": "Personal", "turkish": "Kişisel / Şahsi", "englishSentence": "That's a personal question.", "turkishSentence": "Bu kişisel bir soru." },
    { "english": "International", "turkish": "Uluslararası", "englishSentence": "She works for an international company.", "turkishSentence": "Uluslararası bir şirkette çalışıyor." },
    { "english": "Doctor", "turkish": "Doktor", "englishSentence": "I need to see a doctor.", "turkishSentence": "Bir doktora görünmem gerekiyor." },
    { "english": "Sit", "turkish": "Oturmak", "englishSentence": "Please sit down.", "turkishSentence": "Lütfen oturun." },
    { "english": "Field", "turkish": "Alan / Tarla", "englishSentence": "He works in the field of medicine.", "turkishSentence": "Tıp alanında çalışıyor." },
    { "english": "Write", "turkish": "Yazmak", "englishSentence": "I need to write a letter.", "turkishSentence": "Bir mektup yazmam gerekiyor." },
    { "english": "Necessary", "turkish": "Gerekli / Zorunlu", "englishSentence": "Is it necessary to do this?", "turkishSentence": "Bunu yapmak gerekli mi?" },
    { "english": "Yesterday", "turkish": "Dün", "englishSentence": "I saw her yesterday.", "turkishSentence": "Onu dün gördüm." },
    { "english": "Feeling", "turkish": "Duygu / His", "englishSentence": "I have a bad feeling about this.", "turkishSentence": "Bu konuda kötü bir his var içimde." },
    { "english": "Game", "turkish": "Oyun / Maç", "englishSentence": "The game was very exciting.", "turkishSentence": "Oyun çok heyecanlıydı." },
    { "english": "Team", "turkish": "Takım / Ekip", "englishSentence": "Our team won the match.", "turkishSentence": "Takımımız maçı kazandı." },
    { "english": "Training", "turkish": "Eğitim / Antrenman", "englishSentence": "The training program lasts six months.", "turkishSentence": "Eğitim programı altı ay sürüyor." },
    { "english": "Nature", "turkish": "Doğa / Tabiat", "englishSentence": "I love spending time in nature.", "turkishSentence": "Doğada vakit geçirmeyi seviyorum." },
    { "english": "Voice", "turkish": "Ses", "englishSentence": "She has a beautiful voice.", "turkishSentence": "Güzel bir sesi var." },
    { "english": "Test", "turkish": "Sınav / Test", "englishSentence": "I have a test tomorrow.", "turkishSentence": "Yarın sınavım var." },
    { "english": "Heart", "turkish": "Kalp / Yürek", "englishSentence": "Listen to your heart.", "turkishSentence": "Kalbini dinle." },
    { "english": "Ok", "turkish": "Tamam", "englishSentence": "Ok, I understand.", "turkishSentence": "Tamam, anlıyorum." },
    { "english": "Increase", "turkish": "Artmak / Artırmak", "englishSentence": "Prices continue to increase.", "turkishSentence": "Fiyatlar artmaya devam ediyor." },
    { "english": "Poor", "turkish": "Fakir / Zayıf", "englishSentence": "He comes from a poor family.", "turkishSentence": "Fakir bir aileden geliyor." },
    { "english": "Dad", "turkish": "Baba", "englishSentence": "My dad is the best.", "turkishSentence": "Babam en iyisi." },
    { "english": "Value", "turkish": "Değer", "englishSentence": "Education has great value.", "turkishSentence": "Eğitimin büyük değeri var." },
    { "english": "According", "turkish": "Göre", "englishSentence": "According to the report, sales increased.", "turkishSentence": "Rapora göre satışlar arttı." },
    { "english": "Dr", "turkish": "Doktor (unvan)", "englishSentence": "Dr Smith is a well-known surgeon.", "turkishSentence": "Dr Smith tanınmış bir cerrah." },
    { "english": "Self", "turkish": "Kendilik / Benlik", "englishSentence": "Be true to your self.", "turkishSentence": "Kendine karşı dürüst ol." },
    { "english": "Section", "turkish": "Bölüm / Kısım", "englishSentence": "Read the first section of the book.", "turkishSentence": "Kitabın ilk bölümünü oku." },
    { "english": "Issue", "turkish": "Sorun / Mesele", "englishSentence": "This is a serious issue.", "turkishSentence": "Bu ciddi bir sorun." },
    { "english": "Single", "turkish": "Tek / Bekar", "englishSentence": "I didn't miss a single class.", "turkishSentence": "Tek bir ders bile kaçırmadım." },
    { "english": "Bed", "turkish": "Yatak", "englishSentence": "I go to bed at ten.", "turkishSentence": "Onda yatağa giderim." },
    { "english": "Chance", "turkish": "Şans / Fırsat", "englishSentence": "Give me one more chance.", "turkishSentence": "Bana bir şans daha ver." },
    { "english": "Industry", "turkish": "Sanayi / Endüstri", "englishSentence": "The car industry is growing.", "turkishSentence": "Otomobil sanayisi büyüyor." },
    { "english": "Various", "turkish": "Çeşitli", "englishSentence": "There are various options.", "turkishSentence": "Çeşitli seçenekler var." },
    { "english": "Term", "turkish": "Dönem / Terim", "englishSentence": "The term starts in September.", "turkishSentence": "Dönem eylülde başlıyor." },
    { "english": "Fire", "turkish": "Ateş / Yangın", "englishSentence": "The fire spread quickly.", "turkishSentence": "Yangın hızla yayıldı." },
    { "english": "Speak", "turkish": "Konuşmak", "englishSentence": "Do you speak English?", "turkishSentence": "İngilizce konuşuyor musunuz?" },
    { "english": "Sir", "turkish": "Efendim / Bayım", "englishSentence": "Excuse me, sir.", "turkishSentence": "Affedersiniz, bayım." },
    { "english": "Alone", "turkish": "Yalnız / Tek başına", "englishSentence": "She lives alone.", "turkishSentence": "Yalnız yaşıyor." },
    { "english": "Stand", "turkish": "Ayağa kalkmak / Durmak", "englishSentence": "Please stand up.", "turkishSentence": "Lütfen ayağa kalkın." },
    { "english": "Baby", "turkish": "Bebek", "englishSentence": "The baby is sleeping.", "turkishSentence": "Bebek uyuyor." },
    { "english": "Earlier", "turkish": "Daha önce / Daha erken", "englishSentence": "I should have left earlier.", "turkishSentence": "Daha erken çıkmalıydım." }
];
