// BBC 800 Essential Words - Part 5 (Sub-list 9-10)
const wordsPart5 = [
    // Sub-list 9
    { "english": "Finally", "turkish": "Sonunda", "englishSentence": "We finally arrived home.", "turkishSentence": "Sonunda eve vardık." },
    { "english": "Letter", "turkish": "Mektup / Harf", "englishSentence": "I received a letter from my friend.", "turkishSentence": "Arkadaşımdan bir mektup aldım." },
    { "english": "Hair", "turkish": "Saç", "englishSentence": "She has long hair.", "turkishSentence": "Uzun saçları var." },
    { "english": "Cold", "turkish": "Soğuk", "englishSentence": "It's very cold outside.", "turkishSentence": "Dışarısı çok soğuk." },
    { "english": "Evening", "turkish": "Akşam", "englishSentence": "Good evening, everyone.", "turkishSentence": "İyi akşamlar herkese." },
    { "english": "Quality", "turkish": "Kalite / Nitelik", "englishSentence": "The quality of this product is excellent.", "turkishSentence": "Bu ürünün kalitesi mükemmel." },
    { "english": "Range", "turkish": "Aralık / Menzil / Çeşit", "englishSentence": "We offer a wide range of products.", "turkishSentence": "Geniş bir ürün yelpazesi sunuyoruz." },
    { "english": "Bank", "turkish": "Banka", "englishSentence": "I need to go to the bank.", "turkishSentence": "Bankaya gitmem gerekiyor." },
    { "english": "Central", "turkish": "Merkezi", "englishSentence": "The hotel is in the central area.", "turkishSentence": "Otel merkezi bölgede." },
    { "english": "Hello", "turkish": "Merhaba", "englishSentence": "Hello, how can I help you?", "turkishSentence": "Merhaba, size nasıl yardımcı olabilirim?" },
    { "english": "Happen", "turkish": "Olmak / Gerçekleşmek", "englishSentence": "What happened yesterday?", "turkishSentence": "Dün ne oldu?" },
    { "english": "Ground", "turkish": "Zemin / Yer", "englishSentence": "The ground is wet.", "turkishSentence": "Zemin ıslak." },
    { "english": "Obviously", "turkish": "Açıkça / Belli ki", "englishSentence": "Obviously, he didn't study.", "turkishSentence": "Belli ki çalışmamış." },
    { "english": "Throat", "turkish": "Boğaz", "englishSentence": "I have a sore throat.", "turkishSentence": "Boğazım ağrıyor." },
    { "english": "Hospital", "turkish": "Hastane", "englishSentence": "He was taken to the hospital.", "turkishSentence": "Hastaneye kaldırıldı." },
    { "english": "Amount", "turkish": "Miktar", "englishSentence": "A large amount of money was spent.", "turkishSentence": "Büyük miktarda para harcandı." },
    { "english": "Reading", "turkish": "Okuma", "englishSentence": "Reading is a good habit.", "turkishSentence": "Okumak iyi bir alışkanlıktır." },
    { "english": "East", "turkish": "Doğu", "englishSentence": "The sun rises in the east.", "turkishSentence": "Güneş doğudan doğar." },
    { "english": "Eat", "turkish": "Yemek", "englishSentence": "Let's eat something.", "turkishSentence": "Bir şeyler yiyelim." },
    { "english": "Simply", "turkish": "Basitçe / Sadece", "englishSentence": "I simply don't understand.", "turkishSentence": "Basitçe anlamıyorum." },
    { "english": "Role", "turkish": "Rol", "englishSentence": "She plays an important role.", "turkishSentence": "Önemli bir rol oynuyor." },
    { "english": "Tomorrow", "turkish": "Yarın", "englishSentence": "See you tomorrow.", "turkishSentence": "Yarın görüşürüz." },
    { "english": "Writing", "turkish": "Yazma / Yazı", "englishSentence": "Writing is a useful skill.", "turkishSentence": "Yazmak faydalı bir beceridir." },
    { "english": "Learn", "turkish": "Öğrenmek", "englishSentence": "I want to learn French.", "turkishSentence": "Fransızca öğrenmek istiyorum." },
    { "english": "Walk", "turkish": "Yürümek / Yürüyüş", "englishSentence": "Let's go for a walk.", "turkishSentence": "Yürüyüşe çıkalım." },
    { "english": "Force", "turkish": "Güç / Zorlamak", "englishSentence": "Don't force yourself.", "turkishSentence": "Kendini zorlama." },
    { "english": "Due", "turkish": "Nedeniyle / Beklenen", "englishSentence": "The train is due at noon.", "turkishSentence": "Tren öğlen bekleniyor." },
    { "english": "Return", "turkish": "Dönmek / Geri vermek", "englishSentence": "I will return the book tomorrow.", "turkishSentence": "Kitabı yarın iade edeceğim." },
    { "english": "Price", "turkish": "Fiyat", "englishSentence": "What is the price of this item?", "turkishSentence": "Bu ürünün fiyatı ne?" },
    { "english": "Difference", "turkish": "Fark", "englishSentence": "Can you see the difference?", "turkishSentence": "Farkı görebiliyor musun?" },
    { "english": "Knowledge", "turkish": "Bilgi", "englishSentence": "Knowledge is power.", "turkishSentence": "Bilgi güçtür." },
    { "english": "Break", "turkish": "Kırmak / Mola", "englishSentence": "Let's take a short break.", "turkishSentence": "Kısa bir mola verelim." },
    { "english": "Foreign", "turkish": "Yabancı", "englishSentence": "She speaks three foreign languages.", "turkishSentence": "Üç yabancı dil konuşuyor." },
    { "english": "Hit", "turkish": "Vurmak / Çarpmak", "englishSentence": "He hit the ball hard.", "turkishSentence": "Topa sert vurdu." },
    { "english": "Recent", "turkish": "Son / Yakın zamandaki", "englishSentence": "There have been recent changes.", "turkishSentence": "Son zamanlarda değişiklikler oldu." },
    { "english": "Phone", "turkish": "Telefon", "englishSentence": "My phone battery is dead.", "turkishSentence": "Telefonumun şarjı bitti." },
    { "english": "Brother", "turkish": "Erkek kardeş / Abi", "englishSentence": "My brother is older than me.", "turkishSentence": "Erkek kardeşim benden büyük." },
    { "english": "Project", "turkish": "Proje", "englishSentence": "We are working on a new project.", "turkishSentence": "Yeni bir proje üzerinde çalışıyoruz." },
    { "english": "Lead", "turkish": "Yönetmek / Öncülük etmek", "englishSentence": "She leads the team.", "turkishSentence": "Takımı o yönetiyor." },
    { "english": "Final", "turkish": "Son / Final", "englishSentence": "This is the final decision.", "turkishSentence": "Bu son karar." },
    { "english": "Forward", "turkish": "İleri / İleri doğru", "englishSentence": "We moved forward with the plan.", "turkishSentence": "Planla ilerlemeye devam ettik." },
    { "english": "Decision", "turkish": "Karar", "englishSentence": "It was a difficult decision.", "turkishSentence": "Zor bir karardı." },
    { "english": "Minute", "turkish": "Dakika", "englishSentence": "Wait a minute, please.", "turkishSentence": "Bir dakika bekle lütfen." },
    { "english": "Analysis", "turkish": "Analiz", "englishSentence": "The analysis shows good results.", "turkishSentence": "Analiz iyi sonuçlar gösteriyor." },
    { "english": "Beginning", "turkish": "Başlangıç", "englishSentence": "This is just the beginning.", "turkishSentence": "Bu sadece başlangıç." },
    { "english": "Member", "turkish": "Üye", "englishSentence": "He is a member of the club.", "turkishSentence": "O kulübün bir üyesi." },
    { "english": "Beautiful", "turkish": "Güzel", "englishSentence": "What a beautiful day!", "turkishSentence": "Ne güzel bir gün!" },
    { "english": "Check", "turkish": "Kontrol etmek", "englishSentence": "Let me check the schedule.", "turkishSentence": "Programı kontrol edeyim." },
    { "english": "Post", "turkish": "Gönderi / Posta", "englishSentence": "I need to post this letter.", "turkishSentence": "Bu mektubu postalamam gerekiyor." },
    { "english": "Attention", "turkish": "Dikkat", "englishSentence": "Pay attention to the teacher.", "turkishSentence": "Öğretmene dikkat et." },

    // Sub-list 10
    { "english": "President", "turkish": "Başkan / Cumhurbaşkanı", "englishSentence": "The president gave a speech.", "turkishSentence": "Cumhurbaşkanı bir konuşma yaptı." },
    { "english": "Standard", "turkish": "Standart", "englishSentence": "We must meet the standards.", "turkishSentence": "Standartları karşılamalıyız." },
    { "english": "Wish", "turkish": "Dilek / İstemek", "englishSentence": "I wish you a happy birthday.", "turkishSentence": "Sana mutlu yıllar diliyorum." },
    { "english": "Fun", "turkish": "Eğlence / Eğlenceli", "englishSentence": "Learning can be fun.", "turkishSentence": "Öğrenmek eğlenceli olabilir." },
    { "english": "Production", "turkish": "Üretim", "englishSentence": "Production has increased this year.", "turkishSentence": "Bu yıl üretim arttı." },
    { "english": "Record", "turkish": "Kayıt / Rekor", "englishSentence": "She broke the world record.", "turkishSentence": "Dünya rekorunu kırdı." },
    { "english": "Serious", "turkish": "Ciddi", "englishSentence": "This is a serious matter.", "turkishSentence": "Bu ciddi bir mesele." },
    { "english": "Financial", "turkish": "Finansal / Mali", "englishSentence": "We need financial support.", "turkishSentence": "Finansal desteğe ihtiyacımız var." },
    { "english": "Send", "turkish": "Göndermek", "englishSentence": "I will send you an email.", "turkishSentence": "Sana bir e-posta göndereceğim." },
    { "english": "Trouble", "turkish": "Sorun / Sıkıntı", "englishSentence": "He is in big trouble.", "turkishSentence": "Büyük sıkıntıda." },
    { "english": "Ball", "turkish": "Top", "englishSentence": "Throw me the ball.", "turkishSentence": "Topu bana at." },
    { "english": "Minister", "turkish": "Bakan", "englishSentence": "The minister met with journalists.", "turkishSentence": "Bakan gazetecilerle buluştu." },
    { "english": "Ahead", "turkish": "İleride / Önde", "englishSentence": "Go ahead, I'll follow.", "turkishSentence": "Sen git, ben takip ederim." },
    { "english": "Dog", "turkish": "Köpek", "englishSentence": "The dog is very friendly.", "turkishSentence": "Köpek çok cana yakın." },
    { "english": "Management", "turkish": "Yönetim", "englishSentence": "Good management is essential.", "turkishSentence": "İyi yönetim şarttır." },
    { "english": "Piece", "turkish": "Parça", "englishSentence": "Can I have a piece of cake?", "turkishSentence": "Bir parça kek alabilir miyim?" },
    { "english": "Growth", "turkish": "Büyüme / Gelişme", "englishSentence": "Economic growth is important.", "turkishSentence": "Ekonomik büyüme önemlidir." },
    { "english": "Tonight", "turkish": "Bu gece", "englishSentence": "Are you free tonight?", "turkishSentence": "Bu gece müsait misin?" },
    { "english": "Degree", "turkish": "Derece / Diploma", "englishSentence": "She has a degree in engineering.", "turkishSentence": "Mühendislik diploması var." },
    { "english": "Account", "turkish": "Hesap", "englishSentence": "I opened a bank account.", "turkishSentence": "Bir banka hesabı açtım." },
    { "english": "Interested", "turkish": "İlgili / Meraklı", "englishSentence": "I am interested in history.", "turkishSentence": "Tarihle ilgileniyorum." },
    { "english": "Blood", "turkish": "Kan", "englishSentence": "Blood is thicker than water.", "turkishSentence": "Kan sudan daha yoğundur." },
    { "english": "Lower", "turkish": "Daha düşük / Alçaltmak", "englishSentence": "They lowered the price.", "turkishSentence": "Fiyatı düşürdüler." },
    { "english": "Dear", "turkish": "Sevgili / Değerli", "englishSentence": "Dear friend, how are you?", "turkishSentence": "Sevgili arkadaşım, nasılsın?" },
    { "english": "Size", "turkish": "Boyut / Beden", "englishSentence": "What size do you wear?", "turkishSentence": "Ne beden giyiyorsun?" },
    { "english": "Natural", "turkish": "Doğal", "englishSentence": "This is a natural process.", "turkishSentence": "Bu doğal bir süreç." },
    { "english": "Bill", "turkish": "Fatura / Hesap", "englishSentence": "Can I have the bill, please?", "turkishSentence": "Hesabı alabilir miyim lütfen?" },
    { "english": "Current", "turkish": "Mevcut / Güncel", "englishSentence": "The current situation is stable.", "turkishSentence": "Mevcut durum istikrarlı." },
    { "english": "Date", "turkish": "Tarih / Randevu", "englishSentence": "What is today's date?", "turkishSentence": "Bugünün tarihi ne?" },
    { "english": "Hot", "turkish": "Sıcak", "englishSentence": "The weather is very hot today.", "turkishSentence": "Bugün hava çok sıcak." },
    { "english": "Agree", "turkish": "Katılmak / Hemfikir olmak", "englishSentence": "I agree with your opinion.", "turkishSentence": "Görüşüne katılıyorum." },
    { "english": "Trade", "turkish": "Ticaret", "englishSentence": "International trade is growing.", "turkishSentence": "Uluslararası ticaret büyüyor." },
    { "english": "Recently", "turkish": "Son zamanlarda", "englishSentence": "I have recently moved here.", "turkishSentence": "Son zamanlarda buraya taşındım." },
    { "english": "Normal", "turkish": "Normal", "englishSentence": "Everything is back to normal.", "turkishSentence": "Her şey normale döndü." },
    { "english": "Worth", "turkish": "Değer / Değmek", "englishSentence": "This painting is worth millions.", "turkishSentence": "Bu tablo milyonlar değerinde." },
    { "english": "Modern", "turkish": "Modern / Çağdaş", "englishSentence": "This is a modern building.", "turkishSentence": "Bu modern bir bina." },
    { "english": "List", "turkish": "Liste", "englishSentence": "I made a shopping list.", "turkishSentence": "Alışveriş listesi yaptım." },
    { "english": "Simple", "turkish": "Basit / Sade", "englishSentence": "The answer is simple.", "turkishSentence": "Cevap basit." },
    { "english": "Student", "turkish": "Öğrenci", "englishSentence": "She is a hardworking student.", "turkishSentence": "O çalışkan bir öğrenci." },
    { "english": "Basis", "turkish": "Temel / Esas", "englishSentence": "We meet on a weekly basis.", "turkishSentence": "Haftalık olarak buluşuyoruz." },
    { "english": "Model", "turkish": "Model / Örnek", "englishSentence": "This car is the latest model.", "turkishSentence": "Bu araba en son model." },
    { "english": "Population", "turkish": "Nüfus", "englishSentence": "The population is growing fast.", "turkishSentence": "Nüfus hızla artıyor." },
    { "english": "Blue", "turkish": "Mavi", "englishSentence": "The sky is blue today.", "turkishSentence": "Bugün gökyüzü mavi." },
    { "english": "Hell", "turkish": "Cehennem", "englishSentence": "What the hell happened?", "turkishSentence": "Ne oldu böyle?" },
    { "english": "Summer", "turkish": "Yaz", "englishSentence": "Summer is my favorite season.", "turkishSentence": "Yaz benim en sevdiğim mevsim." },
    { "english": "Floor", "turkish": "Zemin / Kat", "englishSentence": "My office is on the third floor.", "turkishSentence": "Ofisim üçüncü katta." },
    { "english": "Funny", "turkish": "Komik", "englishSentence": "That movie was really funny.", "turkishSentence": "O film gerçekten komikti." },
    { "english": "Choice", "turkish": "Seçim / Tercih", "englishSentence": "You have two choices.", "turkishSentence": "İki seçeneğin var." },
    { "english": "Security", "turkish": "Güvenlik", "englishSentence": "Security is very important.", "turkishSentence": "Güvenlik çok önemlidir." },
    { "english": "Material", "turkish": "Malzeme / Materyal", "englishSentence": "We need more building material.", "turkishSentence": "Daha fazla inşaat malzemesine ihtiyacımız var." }
];
