// BBC 800 Essential Words - Part 7 (Sub-list 12-13)
const wordsPart7 = [
    // Sub-list 12
    { "english": "Kill", "turkish": "Öldürmek", "englishSentence": "Don't kill the spider.", "turkishSentence": "Örümceği öldürme." },
    { "english": "Follow", "turkish": "Takip etmek", "englishSentence": "Follow me, please.", "turkishSentence": "Lütfen beni takip et." },
    { "english": "Function", "turkish": "İşlev / Fonksiyon", "englishSentence": "What is its function?", "turkishSentence": "Bunun işlevi ne?" },
    { "english": "Practice", "turkish": "Pratik / Uygulama", "englishSentence": "Practice makes perfect.", "turkishSentence": "Pratik mükemmelleştirir." },
    { "english": "Former", "turkish": "Eski / Önceki", "englishSentence": "He is the former president.", "turkishSentence": "O eski başkan." },
    { "english": "Sister", "turkish": "Kız kardeş", "englishSentence": "My sister is older than me.", "turkishSentence": "Kız kardeşim benden büyük." },
    { "english": "Absolutely", "turkish": "Kesinlikle", "englishSentence": "I absolutely agree.", "turkishSentence": "Kesinlikle katılıyorum." },
    { "english": "Somewhere", "turkish": "Bir yerde", "englishSentence": "I left it somewhere.", "turkishSentence": "Bir yere bıraktım." },
    { "english": "Include", "turkish": "Dahil etmek", "englishSentence": "Does the price include tax?", "turkishSentence": "Fiyata vergi dahil mi?" },
    { "english": "Sunday", "turkish": "Pazar", "englishSentence": "I rest on Sunday.", "turkishSentence": "Pazar günü dinlenirim." },
    { "english": "Daughter", "turkish": "Kız evlat", "englishSentence": "My daughter is 5 years old.", "turkishSentence": "Kızım 5 yaşında." },
    { "english": "Charge", "turkish": "Şarj / Ücret / Suçlama", "englishSentence": "Is there a charge for this?", "turkishSentence": "Bunun için ücret var mı?" },
    { "english": "Specific", "turkish": "Belirli / Spesifik", "englishSentence": "Give me a specific example.", "turkishSentence": "Bana belirli bir örnek ver." },
    { "english": "Forget", "turkish": "Unutmak", "englishSentence": "Don't forget your keys.", "turkishSentence": "Anahtarlarını unutma." },
    { "english": "Design", "turkish": "Tasarım", "englishSentence": "I love this design.", "turkishSentence": "Bu tasarımı seviyorum." },
    { "english": "Wonder", "turkish": "Merak etmek", "englishSentence": "I wonder what happened.", "turkishSentence": "Ne olduğunu merak ediyorum." },
    { "english": "Shot", "turkish": "Atış / Fotoğraf", "englishSentence": "Nice shot!", "turkishSentence": "Güzel atış!" },
    { "english": "Worry", "turkish": "Endişelenmek", "englishSentence": "Don't worry about it.", "turkishSentence": "Bunun için endişelenme." },
    { "english": "Energy", "turkish": "Enerji", "englishSentence": "I have no energy today.", "turkishSentence": "Bugün hiç enerjim yok." },
    { "english": "Generally", "turkish": "Genellikle", "englishSentence": "Generally, I wake up early.", "turkishSentence": "Genellikle erken kalkarım." },
    { "english": "Wall", "turkish": "Duvar", "englishSentence": "Hang it on the wall.", "turkishSentence": "Duvara as." },
    { "english": "Property", "turkish": "Mülk / Özellik", "englishSentence": "This is private property.", "turkishSentence": "Burası özel mülk." },
    { "english": "Activity", "turkish": "Aktivite / Faaliyet", "englishSentence": "What activity do you like?", "turkishSentence": "Hangi aktiviteyi seversin?" },
    { "english": "Offer", "turkish": "Teklif", "englishSentence": "I'll make you an offer.", "turkishSentence": "Sana bir teklif yapacağım." },
    { "english": "Page", "turkish": "Sayfa", "englishSentence": "Turn to page 10.", "turkishSentence": "10. sayfaya dön." },
    { "english": "Average", "turkish": "Ortalama", "englishSentence": "The average is 50.", "turkishSentence": "Ortalama 50." },
    { "english": "Respect", "turkish": "Saygı", "englishSentence": "Respect is important.", "turkishSentence": "Saygı önemlidir." },
    { "english": "Note", "turkish": "Not", "englishSentence": "Take a note of this.", "turkishSentence": "Bunu not al." },
    { "english": "Treatment", "turkish": "Tedavi", "englishSentence": "The treatment is working.", "turkishSentence": "Tedavi işe yarıyor." },
    { "english": "Station", "turkish": "İstasyon", "englishSentence": "The train station is near.", "turkishSentence": "Tren istasyonu yakın." },
    { "english": "Dinner", "turkish": "Akşam yemeği", "englishSentence": "Let's have dinner.", "turkishSentence": "Akşam yemeği yiyelim." },
    { "english": "Medical", "turkish": "Tıbbi", "englishSentence": "He needs medical help.", "turkishSentence": "Tıbbi yardıma ihtiyacı var." },
    { "english": "Fair", "turkish": "Adil / Fuar", "englishSentence": "That's not fair.", "turkishSentence": "Bu adil değil." },
    { "english": "Patients", "turkish": "Hastalar", "englishSentence": "The doctor sees patients.", "turkishSentence": "Doktor hastaları görüyor." },
    { "english": "Nearly", "turkish": "Neredeyse", "englishSentence": "I'm nearly finished.", "turkishSentence": "Neredeyse bitirdim." },
    { "english": "Quickly", "turkish": "Hızlıca", "englishSentence": "Come here quickly.", "turkishSentence": "Buraya hızlıca gel." },
    { "english": "Purpose", "turkish": "Amaç", "englishSentence": "What is the purpose?", "turkishSentence": "Amaç ne?" },
    { "english": "Teacher", "turkish": "Öğretmen", "englishSentence": "My teacher is great.", "turkishSentence": "Öğretmenim harika." },
    { "english": "Club", "turkish": "Kulüp", "englishSentence": "I joined a sports club.", "turkishSentence": "Bir spor kulübüne katıldım." },
    { "english": "Structure", "turkish": "Yapı", "englishSentence": "The structure is strong.", "turkishSentence": "Yapı sağlam." },
    // Sub-list 13
    { "english": "Television", "turkish": "Televizyon", "englishSentence": "I watch television every day.", "turkishSentence": "Her gün televizyon izlerim." },
    { "english": "Western", "turkish": "Batılı / Batı", "englishSentence": "Western culture is different.", "turkishSentence": "Batı kültürü farklı." },
    { "english": "Opportunity", "turkish": "Fırsat", "englishSentence": "This is a great opportunity.", "turkishSentence": "Bu büyük bir fırsat." },
    { "english": "Key", "turkish": "Anahtar", "englishSentence": "Where is the key?", "turkishSentence": "Anahtar nerede?" },
    { "english": "Series", "turkish": "Dizi / Seri", "englishSentence": "I'm watching a new series.", "turkishSentence": "Yeni bir dizi izliyorum." },
    { "english": "Born", "turkish": "Doğmuş / Doğmak", "englishSentence": "I was born in Istanbul.", "turkishSentence": "İstanbul'da doğdum." },
    { "english": "Park", "turkish": "Park", "englishSentence": "Let's go to the park.", "turkishSentence": "Parka gidelim." },
    { "english": "Response", "turkish": "Yanıt / Cevap", "englishSentence": "I'm waiting for a response.", "turkishSentence": "Bir yanıt bekliyorum." },
    { "english": "Style", "turkish": "Stil / Tarz", "englishSentence": "I like your style.", "turkishSentence": "Tarzını beğeniyorum." },
    { "english": "Hall", "turkish": "Salon / Koridor", "englishSentence": "The hall is big.", "turkishSentence": "Salon büyük." },
    { "english": "Trust", "turkish": "Güven / Güvenmek", "englishSentence": "I trust you.", "turkishSentence": "Sana güveniyorum." },
    { "english": "Window", "turkish": "Pencere", "englishSentence": "Open the window, please.", "turkishSentence": "Pencereyi aç lütfen." },
    { "english": "Dollar", "turkish": "Dolar", "englishSentence": "I have ten dollars.", "turkishSentence": "On dolarım var." },
    { "english": "Carry", "turkish": "Taşımak", "englishSentence": "Can you carry this bag?", "turkishSentence": "Bu çantayı taşıyabilir misin?" },
    { "english": "Square", "turkish": "Kare / Meydan", "englishSentence": "Meet me at the square.", "turkishSentence": "Meydanda buluşalım." },
    { "english": "Direct", "turkish": "Direkt / Yönlendirmek", "englishSentence": "Take the direct route.", "turkishSentence": "Direkt rotayı al." },
    { "english": "Rights", "turkish": "Haklar", "englishSentence": "Know your rights.", "turkishSentence": "Haklarını bil." },
    { "english": "Fight", "turkish": "Kavga / Savaşmak", "englishSentence": "Don't fight with him.", "turkishSentence": "Onunla kavga etme." },
    { "english": "Environment", "turkish": "Çevre", "englishSentence": "Protect the environment.", "turkishSentence": "Çevreyi koru." },
    { "english": "Cool", "turkish": "Havalı / Serin", "englishSentence": "That's really cool!", "turkishSentence": "Bu gerçekten havalı!" },
    { "english": "Sex", "turkish": "Cinsiyet", "englishSentence": "What is your sex?", "turkishSentence": "Cinsiyetiniz ne?" },
    { "english": "Eye", "turkish": "Göz", "englishSentence": "She has blue eyes.", "turkishSentence": "Mavi gözleri var." },
    { "english": "Region", "turkish": "Bölge", "englishSentence": "This region is beautiful.", "turkishSentence": "Bu bölge güzel." },
    { "english": "Original", "turkish": "Orijinal / Özgün", "englishSentence": "Is this the original?", "turkishSentence": "Bu orijinal mi?" },
    { "english": "Brother", "turkish": "Erkek kardeş", "englishSentence": "My brother is a doctor.", "turkishSentence": "Kardeşim doktor." },
    { "english": "Yourself", "turkish": "Kendin", "englishSentence": "Do it yourself.", "turkishSentence": "Kendin yap." },
    { "english": "Anyone", "turkish": "Herhangi biri", "englishSentence": "Does anyone know?", "turkishSentence": "Bilen var mı?" },
    { "english": "Mother", "turkish": "Anne", "englishSentence": "My mother is a teacher.", "turkishSentence": "Annem öğretmen." },
    { "english": "Doctor", "turkish": "Doktor", "englishSentence": "I need to see a doctor.", "turkishSentence": "Doktora görünmem lazım." }
];
