// BBC 800 Essential Words - Part 2 (Sub-list 3-4)
const wordsPart2 = [
    // Sub-list 3
    { "english": "Problem", "turkish": "Sorun / Problem", "englishSentence": "There is a problem with the computer.", "turkishSentence": "Bilgisayarla ilgili bir sorun var." },
    { "english": "Love", "turkish": "Sevgi / Aşk / Sevmek", "englishSentence": "I love my family.", "turkishSentence": "Ailemi seviyorum." },
    { "english": "Real", "turkish": "Gerçek", "englishSentence": "Is this story real?", "turkishSentence": "Bu hikaye gerçek mi?" },
    { "english": "Later", "turkish": "Sonra / Daha sonra", "englishSentence": "See you later!", "turkishSentence": "Sonra görüşürüz!" },
    { "english": "Sorry", "turkish": "Üzgünüm / Özür dilerim", "englishSentence": "Sorry for being late.", "turkishSentence": "Geç kaldığım için özür dilerim." },
    { "english": "Try", "turkish": "Denemek", "englishSentence": "You should try this food.", "turkishSentence": "Bu yemeği denemelisin." },
    { "english": "Best", "turkish": "En iyi", "englishSentence": "She is my best friend.", "turkishSentence": "O benim en iyi arkadaşım." },
    { "english": "Hand", "turkish": "El", "englishSentence": "Raise your hand if you know.", "turkishSentence": "Biliyorsan elini kaldır." },
    { "english": "Show", "turkish": "Göstermek / Gösteri", "englishSentence": "Can you show me the way?", "turkishSentence": "Bana yolu gösterebilir misin?" },
    { "english": "Change", "turkish": "Değişim / Değiştirmek", "englishSentence": "Change is always good.", "turkishSentence": "Değişim her zaman iyidir." },
    { "english": "Name", "turkish": "İsim / Ad", "englishSentence": "What is your name?", "turkishSentence": "Adın ne?" },
    { "english": "Laugh", "turkish": "Gülmek", "englishSentence": "He made everyone laugh.", "turkishSentence": "Herkesi güldürdü." },
    { "english": "Already", "turkish": "Zaten / Çoktan", "englishSentence": "I have already eaten.", "turkishSentence": "Zaten yedim." },
    { "english": "Able", "turkish": "Yapabilir / Muktedir", "englishSentence": "I am able to help you.", "turkishSentence": "Sana yardım edebilirim." },
    { "english": "General", "turkish": "Genel", "englishSentence": "In general, people are friendly here.", "turkishSentence": "Genel olarak, burada insanlar cana yakın." },
    { "english": "Percent", "turkish": "Yüzde", "englishSentence": "There is a fifty percent chance of rain.", "turkishSentence": "Yüzde elli yağmur ihtimali var." },
    { "english": "Room", "turkish": "Oda", "englishSentence": "My room is on the second floor.", "turkishSentence": "Odam ikinci katta." },
    { "english": "Mind", "turkish": "Akıl / Zihin", "englishSentence": "Keep an open mind.", "turkishSentence": "Açık fikirli ol." },
    { "english": "Together", "turkish": "Birlikte", "englishSentence": "We work together.", "turkishSentence": "Birlikte çalışıyoruz." },
    { "english": "Area", "turkish": "Alan / Bölge", "englishSentence": "This area is very quiet.", "turkishSentence": "Bu bölge çok sessiz." },
    { "english": "Call", "turkish": "Aramak / Çağırmak", "englishSentence": "I will call you tomorrow.", "turkishSentence": "Yarın seni arayacağım." },
    { "english": "Remember", "turkish": "Hatırlamak", "englishSentence": "I remember our first meeting.", "turkishSentence": "İlk tanışmamızı hatırlıyorum." },
    { "english": "Thank", "turkish": "Teşekkür etmek", "englishSentence": "Thank you for your help.", "turkishSentence": "Yardımın için teşekkür ederim." },
    { "english": "Order", "turkish": "Sipariş / Düzen", "englishSentence": "I would like to order a coffee.", "turkishSentence": "Bir kahve sipariş etmek istiyorum." },
    { "english": "Believe", "turkish": "İnanmak", "englishSentence": "I believe in you.", "turkishSentence": "Sana inanıyorum." },
    { "english": "Water", "turkish": "Su", "englishSentence": "Drink plenty of water every day.", "turkishSentence": "Her gün bol su iç." },
    { "english": "Nice", "turkish": "Güzel / Hoş", "englishSentence": "It's nice to meet you.", "turkishSentence": "Tanıştığımıza memnun oldum." },
    { "english": "Job", "turkish": "İş", "englishSentence": "He found a new job.", "turkishSentence": "Yeni bir iş buldu." },
    { "english": "Head", "turkish": "Kafa / Baş", "englishSentence": "I have a headache.", "turkishSentence": "Başım ağrıyor." },
    { "english": "Young", "turkish": "Genç", "englishSentence": "He is still very young.", "turkishSentence": "O hâlâ çok genç." },
    { "english": "Important", "turkish": "Önemli", "englishSentence": "This is a very important meeting.", "turkishSentence": "Bu çok önemli bir toplantı." },
    { "english": "Rather", "turkish": "Oldukça / Daha çok", "englishSentence": "I would rather stay home.", "turkishSentence": "Evde kalmayı tercih ederim." },
    { "english": "Business", "turkish": "İş / Ticaret", "englishSentence": "He owns a small business.", "turkishSentence": "Küçük bir işletmeye sahip." },
    { "english": "Least", "turkish": "En az", "englishSentence": "At least try it once.", "turkishSentence": "En azından bir kere dene." },
    { "english": "Power", "turkish": "Güç / Enerji", "englishSentence": "Knowledge is power.", "turkishSentence": "Bilgi güçtür." },
    { "english": "Country", "turkish": "Ülke", "englishSentence": "Turkey is a beautiful country.", "turkishSentence": "Türkiye güzel bir ülke." },
    { "english": "Public", "turkish": "Halk / Kamusal", "englishSentence": "It is a public park.", "turkishSentence": "Burası halka açık bir park." },
    { "english": "Else", "turkish": "Başka / Yoksa", "englishSentence": "What else do you need?", "turkishSentence": "Başka neye ihtiyacın var?" },
    { "english": "Read", "turkish": "Okumak", "englishSentence": "I read a book every week.", "turkishSentence": "Her hafta bir kitap okurum." },
    { "english": "Almost", "turkish": "Neredeyse", "englishSentence": "I am almost finished.", "turkishSentence": "Neredeyse bitirdim." },
    { "english": "Small", "turkish": "Küçük", "englishSentence": "I live in a small apartment.", "turkishSentence": "Küçük bir dairede yaşıyorum." },
    { "english": "Mother", "turkish": "Anne", "englishSentence": "My mother cooks delicious food.", "turkishSentence": "Annem lezzetli yemekler pişirir." },
    { "english": "Group", "turkish": "Grup / Takım", "englishSentence": "We work in a small group.", "turkishSentence": "Küçük bir grupta çalışıyoruz." },
    { "english": "Morning", "turkish": "Sabah", "englishSentence": "Good morning, everyone!", "turkishSentence": "Günaydın herkese!" },
    { "english": "Start", "turkish": "Başlamak", "englishSentence": "Let's start the meeting.", "turkishSentence": "Toplantıya başlayalım." },
    { "english": "Feel", "turkish": "Hissetmek", "englishSentence": "I feel happy today.", "turkishSentence": "Bugün mutlu hissediyorum." },
    { "english": "Less", "turkish": "Daha az", "englishSentence": "Try to eat less sugar.", "turkishSentence": "Daha az şeker yemeye çalış." },
    { "english": "Question", "turkish": "Soru", "englishSentence": "Can I ask you a question?", "turkishSentence": "Sana bir soru sorabilir miyim?" },
    { "english": "Car", "turkish": "Araba", "englishSentence": "He drives a red car.", "turkishSentence": "Kırmızı bir araba kullanıyor." },
    { "english": "Person", "turkish": "Kişi / İnsan", "englishSentence": "She is a kind person.", "turkishSentence": "O nazik bir insan." },

    // Sub-list 4
    { "english": "Company", "turkish": "Şirket / Firma", "englishSentence": "She works for a big company.", "turkishSentence": "Büyük bir şirkette çalışıyor." },
    { "english": "Care", "turkish": "İlgilenmek / Önemsemek", "englishSentence": "I care about the environment.", "turkishSentence": "Çevreyi önemsiyorum." },
    { "english": "Open", "turkish": "Açmak / Açık", "englishSentence": "Open the window, please.", "turkishSentence": "Lütfen pencereyi aç." },
    { "english": "City", "turkish": "Şehir", "englishSentence": "Istanbul is a big city.", "turkishSentence": "İstanbul büyük bir şehir." },
    { "english": "Become", "turkish": "Olmak / Haline gelmek", "englishSentence": "She wants to become a doctor.", "turkishSentence": "Doktor olmak istiyor." },
    { "english": "Perhaps", "turkish": "Belki", "englishSentence": "Perhaps we can meet tomorrow.", "turkishSentence": "Belki yarın buluşabiliriz." },
    { "english": "Ask", "turkish": "Sormak", "englishSentence": "Don't be afraid to ask questions.", "turkishSentence": "Soru sormaktan korkma." },
    { "english": "Pretty", "turkish": "Güzel / Oldukça", "englishSentence": "She is a pretty girl.", "turkishSentence": "O güzel bir kız." },
    { "english": "Possible", "turkish": "Mümkün / Olası", "englishSentence": "Is it possible to finish today?", "turkishSentence": "Bugün bitirmek mümkün mü?" },
    { "english": "Local", "turkish": "Yerel", "englishSentence": "We buy from local farmers.", "turkishSentence": "Yerel çiftçilerden satın alıyoruz." },
    { "english": "Ago", "turkish": "Önce", "englishSentence": "I met her two years ago.", "turkishSentence": "Onunla iki yıl önce tanıştım." },
    { "english": "Social", "turkish": "Sosyal", "englishSentence": "Social media is very popular.", "turkishSentence": "Sosyal medya çok popüler." },
    { "english": "Matter", "turkish": "Mesele / Önemli olmak", "englishSentence": "It doesn't really matter.", "turkishSentence": "Gerçekten önemli değil." },
    { "english": "Cause", "turkish": "Sebep / Neden olmak", "englishSentence": "What caused the accident?", "turkishSentence": "Kazaya ne sebep oldu?" },
    { "english": "Run", "turkish": "Koşmak", "englishSentence": "I run every morning.", "turkishSentence": "Her sabah koşuyorum." },
    { "english": "Hard", "turkish": "Zor / Sert", "englishSentence": "This is a hard question.", "turkishSentence": "Bu zor bir soru." },
    { "english": "National", "turkish": "Ulusal", "englishSentence": "Today is a national holiday.", "turkishSentence": "Bugün ulusal bir tatil." },
    { "english": "Information", "turkish": "Bilgi", "englishSentence": "I need more information.", "turkishSentence": "Daha fazla bilgiye ihtiyacım var." },
    { "english": "Form", "turkish": "Form / Biçim", "englishSentence": "Please fill out this form.", "turkishSentence": "Lütfen bu formu doldurun." },
    { "english": "Book", "turkish": "Kitap", "englishSentence": "I am reading a book.", "turkishSentence": "Bir kitap okuyorum." },
    { "english": "Hey", "turkish": "Hey / Selam", "englishSentence": "Hey, how are you?", "turkishSentence": "Hey, nasılsın?" },
    { "english": "Present", "turkish": "Mevcut / Hediye / Sunmak", "englishSentence": "I have a present for you.", "turkishSentence": "Senin için bir hediyem var." },
    { "english": "Leave", "turkish": "Ayrılmak / Bırakmak", "englishSentence": "I have to leave now.", "turkishSentence": "Şimdi gitmem gerekiyor." },
    { "english": "Anyway", "turkish": "Her neyse / Zaten", "englishSentence": "Anyway, let's continue.", "turkishSentence": "Her neyse, devam edelim." },
    { "english": "Full", "turkish": "Dolu / Tam", "englishSentence": "The bus is full.", "turkishSentence": "Otobüs dolu." },
    { "english": "Party", "turkish": "Parti / Kutlama", "englishSentence": "We had a great party last night.", "turkishSentence": "Dün gece harika bir parti yaptık." },
    { "english": "Father", "turkish": "Baba", "englishSentence": "My father is a doctor.", "turkishSentence": "Babam bir doktor." },
    { "english": "Face", "turkish": "Yüz", "englishSentence": "She has a beautiful face.", "turkishSentence": "Güzel bir yüzü var." },
    { "english": "Service", "turkish": "Hizmet / Servis", "englishSentence": "The service here is excellent.", "turkishSentence": "Buradaki hizmet mükemmel." },
    { "english": "Office", "turkish": "Ofis", "englishSentence": "I work in an office.", "turkishSentence": "Bir ofiste çalışıyorum." },
    { "english": "Means", "turkish": "Araç / Yol", "englishSentence": "Money is a means to an end.", "turkishSentence": "Para bir amaca ulaşmak için araçtır." },
    { "english": "Bad", "turkish": "Kötü", "englishSentence": "That's not a bad idea.", "turkishSentence": "O kötü bir fikir değil." },
    { "english": "Early", "turkish": "Erken", "englishSentence": "I wake up early every morning.", "turkishSentence": "Her sabah erken kalkıyorum." },
    { "english": "Stuff", "turkish": "Malzeme / Şeyler", "englishSentence": "I have a lot of stuff to do.", "turkishSentence": "Yapacak çok işim var." },
    { "english": "Live", "turkish": "Yaşamak / Canlı", "englishSentence": "Where do you live?", "turkishSentence": "Nerede yaşıyorsun?" },
    { "english": "Often", "turkish": "Sık sık", "englishSentence": "I often go running in the morning.", "turkishSentence": "Sabahları sık sık koşuya giderim." },
    { "english": "War", "turkish": "Savaş", "englishSentence": "Nobody wants war.", "turkishSentence": "Kimse savaş istemez." },
    { "english": "Please", "turkish": "Lütfen", "englishSentence": "Please help me.", "turkishSentence": "Lütfen bana yardım et." },
    { "english": "Idea", "turkish": "Fikir", "englishSentence": "That's a great idea!", "turkishSentence": "Bu harika bir fikir!" },
    { "english": "Example", "turkish": "Örnek", "englishSentence": "Can you give me an example?", "turkishSentence": "Bana bir örnek verebilir misin?" },
    { "english": "Large", "turkish": "Büyük / Geniş", "englishSentence": "We live in a large house.", "turkishSentence": "Büyük bir evde yaşıyoruz." },
    { "english": "Pay", "turkish": "Ödemek / Ücret", "englishSentence": "I need to pay the bill.", "turkishSentence": "Faturayı ödemem gerekiyor." },
    { "english": "Line", "turkish": "Çizgi / Sıra / Hat", "englishSentence": "Please stand in line.", "turkishSentence": "Lütfen sıraya girin." },
    { "english": "Play", "turkish": "Oynamak / Çalmak", "englishSentence": "Children love to play outside.", "turkishSentence": "Çocuklar dışarıda oynamayı sever." },
    { "english": "True", "turkish": "Doğru / Gerçek", "englishSentence": "Is this story true?", "turkishSentence": "Bu hikaye doğru mu?" },
    { "english": "Woman", "turkish": "Kadın", "englishSentence": "She is a strong woman.", "turkishSentence": "O güçlü bir kadın." },
    { "english": "Guess", "turkish": "Tahmin etmek", "englishSentence": "I guess you're right.", "turkishSentence": "Sanırım haklısın." },
    { "english": "Development", "turkish": "Gelişim / Kalkınma", "englishSentence": "The city is under development.", "turkishSentence": "Şehir gelişim sürecinde." },
    { "english": "Level", "turkish": "Seviye / Düzey", "englishSentence": "What is your English level?", "turkishSentence": "İngilizce seviyen ne?" },
    { "english": "Understand", "turkish": "Anlamak", "englishSentence": "I don't understand this.", "turkishSentence": "Bunu anlamıyorum." }
];
