// BBC 800 Essential Words - Part 4 (Sub-list 8-10)
const wordsPart4 = [
    // Sub-list 7-8
    { "english": "Exactly", "turkish": "Tam olarak / Aynen", "englishSentence": "That's exactly what I meant.", "turkishSentence": "Tam olarak bunu kastetmiştim." },
    { "english": "Main", "turkish": "Ana / Asıl", "englishSentence": "What is the main point?", "turkishSentence": "Ana nokta ne?" },
    { "english": "Rest", "turkish": "Dinlenme / Geri kalan", "englishSentence": "Take some rest.", "turkishSentence": "Biraz dinlen." },
    { "english": "Son", "turkish": "Oğul", "englishSentence": "He has one son.", "turkishSentence": "Bir oğlu var." },
    { "english": "Miss", "turkish": "Bayan / Özlemek / Kaçırmak", "englishSentence": "I miss my family.", "turkishSentence": "Ailemi özlüyorum." },
    { "english": "North", "turkish": "Kuzey", "englishSentence": "They live in the north.", "turkishSentence": "Kuzeyde yaşıyorlar." },
    { "english": "Hi", "turkish": "Merhaba / Selam", "englishSentence": "Hi, how are you?", "turkishSentence": "Selam, nasılsın?" },
    { "english": "Staff", "turkish": "Personel", "englishSentence": "The staff is very helpful.", "turkishSentence": "Personel çok yardımsever." },
    { "english": "Stage", "turkish": "Sahne / Aşama", "englishSentence": "The project is in its final stage.", "turkishSentence": "Proje son aşamasında." },
    { "english": "Hold", "turkish": "Tutmak", "englishSentence": "Hold my hand.", "turkishSentence": "Elimi tut." },
    { "english": "Happy", "turkish": "Mutlu", "englishSentence": "I am very happy today.", "turkishSentence": "Bugün çok mutluyum." },
    { "english": "Result", "turkish": "Sonuç", "englishSentence": "What was the result?", "turkishSentence": "Sonuç ne oldu?" },
    { "english": "Board", "turkish": "Tahta / Kurul", "englishSentence": "Write it on the board.", "turkishSentence": "Tahtaya yaz." },
    { "english": "Committee", "turkish": "Komite", "englishSentence": "The committee will decide.", "turkishSentence": "Komite karar verecek." },
    { "english": "Especially", "turkish": "Özellikle", "englishSentence": "I love music, especially jazz.", "turkishSentence": "Müziği severim, özellikle cazı." },
    { "english": "Building", "turkish": "Bina", "englishSentence": "That building is very tall.", "turkishSentence": "O bina çok yüksek." },
    { "english": "Plan", "turkish": "Plan / Planlamak", "englishSentence": "What is your plan?", "turkishSentence": "Planın ne?" },
    { "english": "Husband", "turkish": "Koca / Eş", "englishSentence": "Her husband is a teacher.", "turkishSentence": "Kocası öğretmen." },
    { "english": "Tax", "turkish": "Vergi", "englishSentence": "We have to pay tax.", "turkishSentence": "Vergi ödemek zorundayız." },
    { "english": "Thanks", "turkish": "Teşekkürler", "englishSentence": "Thanks for your help.", "turkishSentence": "Yardımın için teşekkürler." },
    { "english": "Instead", "turkish": "Bunun yerine", "englishSentence": "Let's walk instead of driving.", "turkishSentence": "Araba kullanmak yerine yürüyelim." },
    { "english": "Ready", "turkish": "Hazır", "englishSentence": "Are you ready to go?", "turkishSentence": "Gitmeye hazır mısın?" },
    { "english": "Individual", "turkish": "Birey / Bireysel", "englishSentence": "Every individual is unique.", "turkishSentence": "Her birey özeldir." },
    { "english": "Listen", "turkish": "Dinlemek", "englishSentence": "Listen to me carefully.", "turkishSentence": "Beni dikkatlice dinle." },
    { "english": "Middle", "turkish": "Orta / Ortası", "englishSentence": "Stand in the middle.", "turkishSentence": "Ortada dur." },
    { "english": "Action", "turkish": "Eylem / Aksiyon", "englishSentence": "We need to take action now.", "turkishSentence": "Şimdi harekete geçmeliyiz." },
    { "english": "Sound", "turkish": "Ses", "englishSentence": "What was that sound?", "turkishSentence": "O ses neydi?" },
    { "english": "Similar", "turkish": "Benzer", "englishSentence": "These two are very similar.", "turkishSentence": "Bu ikisi çok benzer." },
    { "english": "Likely", "turkish": "Muhtemel / Olası", "englishSentence": "It's likely to rain today.", "turkishSentence": "Bugün yağmur yağması muhtemel." },
    { "english": "Field", "turkish": "Alan / Tarla", "englishSentence": "He works in the medical field.", "turkishSentence": "Tıp alanında çalışıyor." },
    { "english": "Write", "turkish": "Yazmak", "englishSentence": "Can you write your name here?", "turkishSentence": "Adını buraya yazabilir misin?" },
    { "english": "Necessary", "turkish": "Gerekli", "englishSentence": "Sleep is necessary for health.", "turkishSentence": "Uyku sağlık için gereklidir." },
    { "english": "Yesterday", "turkish": "Dün", "englishSentence": "I saw him yesterday.", "turkishSentence": "Onu dün gördüm." },
    { "english": "Feeling", "turkish": "His / Duygu", "englishSentence": "I have a good feeling about this.", "turkishSentence": "Bu konuda iyi hissediyorum." },
    { "english": "Voice", "turkish": "Ses", "englishSentence": "She has a beautiful voice.", "turkishSentence": "Güzel bir sesi var." },
    { "english": "Game", "turkish": "Oyun / Maç", "englishSentence": "Let's play a game.", "turkishSentence": "Bir oyun oynayalım." },
    { "english": "Team", "turkish": "Takım / Ekip", "englishSentence": "We are a strong team.", "turkishSentence": "Güçlü bir takımız." },
    { "english": "Training", "turkish": "Eğitim / Antrenman", "englishSentence": "The training starts tomorrow.", "turkishSentence": "Eğitim yarın başlıyor." },
    { "english": "Nature", "turkish": "Doğa", "englishSentence": "I love nature.", "turkishSentence": "Doğayı seviyorum." },
    { "english": "Poor", "turkish": "Fakir / Zayıf", "englishSentence": "They help the poor.", "turkishSentence": "Fakirlere yardım ediyorlar." },
    { "english": "Self", "turkish": "Kendi / Benlik", "englishSentence": "Believe in yourself.", "turkishSentence": "Kendine inan." },
    { "english": "Test", "turkish": "Test / Sınav", "englishSentence": "I have a test tomorrow.", "turkishSentence": "Yarın sınavım var." },
    { "english": "Heart", "turkish": "Kalp", "englishSentence": "Follow your heart.", "turkishSentence": "Kalbini takip et." },
    { "english": "Ok", "turkish": "Tamam", "englishSentence": "Ok, I understand.", "turkishSentence": "Tamam, anladım." },
    { "english": "Increase", "turkish": "Artış / Artırmak", "englishSentence": "Prices will increase.", "turkishSentence": "Fiyatlar artacak." },
    { "english": "Speak", "turkish": "Konuşmak", "englishSentence": "Can you speak English?", "turkishSentence": "İngilizce konuşabiliyor musun?" },
    { "english": "Sit", "turkish": "Oturmak", "englishSentence": "Please sit down.", "turkishSentence": "Lütfen otur." },
    { "english": "Chance", "turkish": "Şans / Fırsat", "englishSentence": "Give me one more chance.", "turkishSentence": "Bana bir şans daha ver." },
    { "english": "Dad", "turkish": "Baba", "englishSentence": "My dad is at work.", "turkishSentence": "Babam işte." },
    { "english": "Value", "turkish": "Değer", "englishSentence": "Family has great value.", "turkishSentence": "Ailenin büyük değeri var." },
    { "english": "According", "turkish": "-e göre", "englishSentence": "According to the news...", "turkishSentence": "Haberlere göre..." },
    { "english": "Dr", "turkish": "Doktor", "englishSentence": "Dr Smith is a good doctor.", "turkishSentence": "Dr Smith iyi bir doktor." },
    { "english": "Section", "turkish": "Bölüm / Kesim", "englishSentence": "Read this section carefully.", "turkishSentence": "Bu bölümü dikkatle oku." },
    { "english": "Issue", "turkish": "Sorun / Konu", "englishSentence": "This is an important issue.", "turkishSentence": "Bu önemli bir konu." },
    { "english": "Single", "turkish": "Tek / Bekar", "englishSentence": "I am still single.", "turkishSentence": "Hâlâ bekarım." },
    { "english": "Bed", "turkish": "Yatak", "englishSentence": "The bed is very comfortable.", "turkishSentence": "Yatak çok rahat." },
    { "english": "Fire", "turkish": "Ateş / Yangın", "englishSentence": "Call the fire department!", "turkishSentence": "İtfaiyeyi ara!" },
    { "english": "Earlier", "turkish": "Daha önce", "englishSentence": "I saw this earlier today.", "turkishSentence": "Bunu bugün daha önce gördüm." },
    { "english": "Industry", "turkish": "Endüstri / Sanayi", "englishSentence": "The car industry is growing.", "turkishSentence": "Otomobil sanayi büyüyor." },
    { "english": "Various", "turkish": "Çeşitli", "englishSentence": "There are various options.", "turkishSentence": "Çeşitli seçenekler var." },
    { "english": "Term", "turkish": "Dönem / Terim", "englishSentence": "What does this term mean?", "turkishSentence": "Bu terim ne anlama geliyor?" },
    { "english": "Alone", "turkish": "Yalnız", "englishSentence": "I like being alone sometimes.", "turkishSentence": "Bazen yalnız olmayı severim." },
    { "english": "Stand", "turkish": "Ayakta durmak", "englishSentence": "Please stand up.", "turkishSentence": "Lütfen ayağa kalk." },
    { "english": "Baby", "turkish": "Bebek", "englishSentence": "The baby is sleeping.", "turkishSentence": "Bebek uyuyor." },
    { "english": "Sir", "turkish": "Efendim / Bayım", "englishSentence": "How can I help you, sir?", "turkishSentence": "Size nasıl yardımcı olabilirim, efendim?" }
];
