// BBC 800 Essential Words - Part 3 (Sub-list 6-8)
const wordsPart3 = [
    // Sub-list 6 continued
    { "english": "Wait", "turkish": "Beklemek", "englishSentence": "Please wait here.", "turkishSentence": "Lütfen burada bekle." },
    { "english": "Road", "turkish": "Yol", "englishSentence": "The road is very long.", "turkishSentence": "Yol çok uzun." },
    { "english": "Particular", "turkish": "Belirli / Özel", "englishSentence": "Is there a particular reason?", "turkishSentence": "Belirli bir sebep var mı?" },
    { "english": "Paper", "turkish": "Kağıt", "englishSentence": "I need a piece of paper.", "turkishSentence": "Bir kağıda ihtiyacım var." },
    { "english": "View", "turkish": "Görüş / Manzara", "englishSentence": "The view from here is amazing.", "turkishSentence": "Buradan manzara muhteşem." },
    { "english": "Major", "turkish": "Büyük / Ana", "englishSentence": "This is a major problem.", "turkishSentence": "Bu büyük bir problem." },
    { "english": "Thinking", "turkish": "Düşünme", "englishSentence": "I was thinking about you.", "turkishSentence": "Seni düşünüyordum." },
    { "english": "Late", "turkish": "Geç", "englishSentence": "Sorry, I'm late.", "turkishSentence": "Özür dilerim, geç kaldım." },
    { "english": "Short", "turkish": "Kısa", "englishSentence": "It was a short meeting.", "turkishSentence": "Kısa bir toplantıydı." },
    { "english": "Mrs.", "turkish": "Bayan", "englishSentence": "Mrs. Smith is our teacher.", "turkishSentence": "Bayan Smith bizim öğretmenimiz." },
    { "english": "Deal", "turkish": "Anlaşma / İlgilenmek", "englishSentence": "We have a deal.", "turkishSentence": "Anlaştık." },
    { "english": "News", "turkish": "Haber", "englishSentence": "Did you hear the news?", "turkishSentence": "Haberi duydun mu?" },
    { "english": "Market", "turkish": "Pazar / Piyasa", "englishSentence": "I'm going to the market.", "turkishSentence": "Pazara gidiyorum." },
    { "english": "South", "turkish": "Güney", "englishSentence": "They live in the south.", "turkishSentence": "Güneyde yaşıyorlar." },
    { "english": "Cost", "turkish": "Maliyet / Fiyat", "englishSentence": "How much does it cost?", "turkishSentence": "Ne kadar?" },
    { "english": "Difficult", "turkish": "Zor", "englishSentence": "This is a difficult question.", "turkishSentence": "Bu zor bir soru." },
    { "english": "Future", "turkish": "Gelecek", "englishSentence": "The future is uncertain.", "turkishSentence": "Gelecek belirsiz." },
    { "english": "Age", "turkish": "Yaş / Çağ", "englishSentence": "What is your age?", "turkishSentence": "Yaşın kaç?" },
    { "english": "Report", "turkish": "Rapor", "englishSentence": "I finished the report.", "turkishSentence": "Raporu bitirdim." },
    { "english": "Friend", "turkish": "Arkadaş", "englishSentence": "She is my best friend.", "turkishSentence": "O benim en iyi arkadaşım." },
    { "english": "Town", "turkish": "Kasaba / Şehir", "englishSentence": "It's a small town.", "turkishSentence": "Küçük bir kasaba." },
    { "english": "Death", "turkish": "Ölüm", "englishSentence": "Death is part of life.", "turkishSentence": "Ölüm hayatın bir parçası." },
    { "english": "Figure", "turkish": "Rakam / Figür", "englishSentence": "Check these figures.", "turkishSentence": "Bu rakamları kontrol et." },
    { "english": "Land", "turkish": "Toprak / Kara", "englishSentence": "We bought some land.", "turkishSentence": "Biraz arazi satın aldık." },
    { "english": "Process", "turkish": "Süreç / İşlem", "englishSentence": "The process takes time.", "turkishSentence": "Süreç zaman alır." },
    { "english": "Meeting", "turkish": "Toplantı", "englishSentence": "The meeting starts at 10.", "turkishSentence": "Toplantı saat 10'da başlar." },
    { "english": "Support", "turkish": "Destek", "englishSentence": "Thank you for your support.", "turkishSentence": "Desteğin için teşekkürler." },
    { "english": "Clear", "turkish": "Açık / Net", "englishSentence": "The instructions are clear.", "turkishSentence": "Talimatlar açık." },
    { "english": "Police", "turkish": "Polis", "englishSentence": "Call the police!", "turkishSentence": "Polisi ara!" },
    { "english": "Department", "turkish": "Departman / Bölüm", "englishSentence": "I work in the sales department.", "turkishSentence": "Satış departmanında çalışıyorum." },
    { "english": "Society", "turkish": "Toplum", "englishSentence": "We live in a modern society.", "turkishSentence": "Modern bir toplumda yaşıyoruz." },
    { "english": "Policy", "turkish": "Politika", "englishSentence": "What is the company policy?", "turkishSentence": "Şirket politikası ne?" },
    { "english": "Table", "turkish": "Masa", "englishSentence": "Put the book on the table.", "turkishSentence": "Kitabı masaya koy." },
    { "english": "History", "turkish": "Tarih", "englishSentence": "I love studying history.", "turkishSentence": "Tarih çalışmayı seviyorum." },
    { "english": "Special", "turkish": "Özel", "englishSentence": "Today is a special day.", "turkishSentence": "Bugün özel bir gün." },
    { "english": "Type", "turkish": "Tür / Tip", "englishSentence": "What type of music do you like?", "turkishSentence": "Ne tür müzik seversin?" },
    { "english": "Seem", "turkish": "Görünmek / Gibi olmak", "englishSentence": "You seem tired today.", "turkishSentence": "Bugün yorgun görünüyorsun." },
    { "english": "Experience", "turkish": "Deneyim / Tecrübe", "englishSentence": "I have five years of experience.", "turkishSentence": "Beş yıllık deneyimim var." },
    { "english": "Couple", "turkish": "Çift / Birkaç", "englishSentence": "I need a couple of minutes.", "turkishSentence": "Birkaç dakikaya ihtiyacım var." },
    { "english": "Centre", "turkish": "Merkez", "englishSentence": "The mall is in the city centre.", "turkishSentence": "AVM şehir merkezinde." },
    { "english": "Street", "turkish": "Sokak", "englishSentence": "I live on Main Street.", "turkishSentence": "Ana Sokak'ta yaşıyorum." },
    { "english": "Interesting", "turkish": "İlginç", "englishSentence": "That's an interesting idea.", "turkishSentence": "Bu ilginç bir fikir." },
    // Sub-list 7
    { "english": "Situation", "turkish": "Durum", "englishSentence": "This is a difficult situation.", "turkishSentence": "Bu zor bir durum." },
    { "english": "Available", "turkish": "Mevcut / Müsait", "englishSentence": "Is this room available?", "turkishSentence": "Bu oda müsait mi?" },
    { "english": "Low", "turkish": "Düşük / Alçak", "englishSentence": "The price is very low.", "turkishSentence": "Fiyat çok düşük." },
    { "english": "Effect", "turkish": "Etki", "englishSentence": "What is the effect of this?", "turkishSentence": "Bunun etkisi ne?" },
    { "english": "Private", "turkish": "Özel / Gizli", "englishSentence": "This is a private matter.", "turkishSentence": "Bu özel bir mesele." },
    { "english": "Alright", "turkish": "Tamam / İyi", "englishSentence": "Is everything alright?", "turkishSentence": "Her şey yolunda mı?" },
    { "english": "Mum", "turkish": "Anne", "englishSentence": "I called my mum yesterday.", "turkishSentence": "Dün annemi aradım." },
    { "english": "Meet", "turkish": "Tanışmak / Buluşmak", "englishSentence": "Nice to meet you.", "turkishSentence": "Tanıştığıma memnun oldum." },
    { "english": "Subject", "turkish": "Konu / Ders", "englishSentence": "Math is my favorite subject.", "turkishSentence": "Matematik en sevdiğim ders." },
    { "english": "Easy", "turkish": "Kolay", "englishSentence": "This is easy to understand.", "turkishSentence": "Bunu anlamak kolay." },
    { "english": "Month", "turkish": "Ay", "englishSentence": "We will meet next month.", "turkishSentence": "Gelecek ay buluşacağız." },
    { "english": "Court", "turkish": "Mahkeme", "englishSentence": "He went to court today.", "turkishSentence": "Bugün mahkemeye gitti." },
    { "english": "Church", "turkish": "Kilise", "englishSentence": "The church is on the corner.", "turkishSentence": "Kilise köşede." },
    { "english": "West", "turkish": "Batı", "englishSentence": "The sun sets in the west.", "turkishSentence": "Güneş batıda batar." },
    { "english": "College", "turkish": "Kolej / Üniversite", "englishSentence": "She goes to college in London.", "turkishSentence": "Londra'da üniversiteye gidiyor." },
    { "english": "Evidence", "turkish": "Kanıt / Delil", "englishSentence": "There is no evidence.", "turkishSentence": "Hiçbir kanıt yok." },
    { "english": "Total", "turkish": "Toplam", "englishSentence": "What is the total cost?", "turkishSentence": "Toplam maliyet ne?" }
];
